README.md
build.sbt
cli/src/main/scala/scalafix/cli/Cli.scala
cli/src/main/scala/scalafix/cli/termdisplay/TermDisplay.scala
cli/src/test/scala/scalafix/cli/CliSuite.scala

This project is currently so small so any red line has a huge impact on
coveerage.  TermDisplay was mostly copy-pasted from coursier, so I'm OK
with excluding that from coverage.

Bump code coverage.

---

.drone.yml
build.sbt
project/Build.scala
scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscComponent.scala
scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
scalafix-tests/src/test/scala/scalafix/tests/IntegrationPropertyTest.scala

Fix bug in integration tests

---

.scalafix.conf
build.sbt
cli/src/main/scala/scalafix/cli/ArgParserImplicits.scala
cli/src/main/scala/scalafix/cli/Cli.scala
cli/src/test/scala/scalafix/cli/CliTest.scala
core/src/main/scala/scalafix/config/ScalafixConfig.scala
core/src/main/scala/scalafix/config/ScalafixMetaconfigReaders.scala
core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
core/src/main/scala/scalafix/syntax/package.scala

Supprt for
- custom out file
- parsing .scalafix.conf

Revive the command line interface.

---

core/src/main/scala/scalafix/util/CanonicalImport.scala
core/src/main/scala/scalafix/util/OrganizeImports.scala
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsBase.source
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsRemoveUnused.source

Keep Importee.Name with wildcard imports

---

core/src/main/scala/scalafix/syntax/package.scala
core/src/main/scala/scalafix/util/OrganizeImports.scala
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsBase.source
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsRemoveUnused.source
scalafix-nsc/src/test/scala/scalafix/SemanticTests.scala
scalafix-nsc/src/test/scala/scalafix/test/Generic.scala

Remove false "wildard subsumes" assumption

---

core/src/main/scala/scalafix/config/ImportsConfig.scala

Disable imports.expandRelative by default

---

core/src/main/scala/scalafix/util/CanonicalImport.scala
core/src/main/scala/scalafix/util/OrganizeImports.scala

Ensure that expanded relative imports inherit _root_.

---

cli/src/main/scala/scalafix/cli/ClasspathOps.scala
cli/src/main/scala/scalafix/cli/Cli.scala
core/src/main/scala/scalafix/rewrite/ScalaJsRewrites.scala
core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
core/src/main/scala/scalafix/util/CanonicalImport.scala
core/src/main/scala/scalafix/util/OrganizeImports.scala
readme/Faq.scalatex
readme/Readme.scalatex
rewrites/MyRewrite.scala
scalafix-nsc/src/main/scala/scalafix/nsc/HijackImportInfos.scala
scalafix-nsc/src/main/scala/scalafix/nsc/NscScalafixMirror.scala
scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscComponent.scala
scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscPlugin.scala
scalafix-nsc/src/test/resources/checkSyntax/DemandJsGlobal.source
scalafix-nsc/src/test/resources/checkSyntax/FlipEither.source
scalafix-nsc/src/test/resources/checkSyntax/FqnRewrite.source
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsBase.source
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsNoGroups.source
scalafix-nsc/src/test/resources/checkSyntax/OrganizeImportsRemoveUnused.source
scalafix-nsc/src/test/scala/scala/scalajs/js.scala
scalafix-nsc/src/test/scala/scala/scalajs/js/GlobalScope.scala
scalafix-nsc/src/test/scala/scala/scalajs/js/Object.scala
scalafix-nsc/src/test/scala/scala/scalajs/js/annotation/JSGlobal.scala
scalafix-nsc/src/test/scala/scala/scalajs/js/annotation/JSName.scala
scalafix-nsc/src/test/scala/scala/scalajs/js/annotation/falsealarm/js.scala
scalafix-nsc/src/test/scala/scalafix/SemanticTests.scala
scalafix-tests/src/test/scala/scalafix/tests/IntegrationPropertyTest.scala

cc https://github.com/scala-js/scala-js/pull/2794#issuecomment-284431494

Implement basic "Demand @JSGlobal" rewrite.

---

scalafix-tests/src/test/scala/scalafix/tests/IntegrationPropertyTest.scala

I'm surprised this got past CI.

Bump up stack size in integration tests.

---

build.sbt
cli/src/main/scala/scalafix/cli/Cli.scala
project/Dependencies.scala

Adds CLI options for classpath and sourcepath, and constructs a mirror using them.
Fixes #106.

Add CLI options for classpath and sourcepath

---

readme/Rewrites.scalatex

I forgot to do it in #129 
Tested locally:

Add docs for ExplicitUnit

---

scalafix-core/src/main/scala/scalafix/rewrite/SemanticPatchOps.scala

These were useful for this rewrite here:
https://github.com/scalacenter/scalafix/commit/5865d681bb6c91313dd1039b529c72c1c126baad

Add remove/replace token patches.

---

readme/Rewrites.scalatex

I forgot to include it in #143 
Tested locally:

Add docs for NoAutoTupling

---

scalafix-tests/src/test/resources/checkSyntax/NoAutoTupling.source

Add NoAutoTupling test cases involving classes and case classes

---

readme/Rewrites.scalatex
scalafix-core/src/main/scala/scalafix/rewrite/NoValInForComprehension.scala
scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
scalafix-tests/src/test/resources/checkSyntax/NoValInForComprehension.source

Closes #153 
I couldn't come up with many creative tests for this, but I'd be glad to add more edge cases if anyone can think of any.

Add NoValInForComprehension syntactic rewrite

---

README.md

Gabriele contributed over half of the new features in the latest v0.4
release. His input and feedback in the issue tracker and offline
discussions has also been very valuable. Thank you!

Welcome Gabriele Petronella to the team!

---

project/plugins.sbt

I enable it on my local laptop with an ignored sbt file.

Disable sbt-errors-summary by default.

---

build.sbt

Don't compile dotty output with 2.x in CI

---

scalafix-core/src/main/scala/scalafix/rewrite/RemoveUnusedImports.scala
scalafix-tests/input/src/main/scala/test/RemoveUnusedImports.scala

Handle Importee.Rename in RemoveUnusedImports, fixes #189

---

readme/Rewrites.scalatex
scalafix-core/src/main/scala/scalafix/rewrite/NoExtendsApp.scala
scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
scalafix-tests/input/src/main/scala/test/NoExtendsApp.scala
scalafix-tests/output/src/main/scala/test/NoExtendsApp.scala

Add NoExtendsApp rewrite

---

build.sbt
project/plugins.sbt
readme/ImplementingRewrites.scalatex
scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala
scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRewriteSuite.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/GitHubUrlRewriteSuite.scala

I hadn't actually tried it yet, whoops. This expansion should match the
boilerplate created by g8 scalacenter/scalafix.g8

Fine-tune github: protocol.

---

scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala
scalafix-core/shared/src/main/scala/scalafix/rewrite/RewriteCtx.scala

Add replaceSymbol to PatchOps

---

scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
scalafix-cli/src/main/scala/scalafix/internal/cli/ScalafixOptions.scala
scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/project/project/plugins.sbt
scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/sbtfix-me.sbt
scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
scalafix-sbt/src/test-project-template/project/ScalafixTestUtility.scala
scalafix-sbt/src/test-project-template/project/plugins.sbt
scalafix-tests/unit/src/test/scala/scalafix/cli/AutoClasspathSuite.scala

While testing out sbtfix on some larger projects I hit on errors. This PR fixes those issues and adds infrastructure for sbtfix integration tests.

Sbtfix integration issues

---

readme/ImplementingRules.scalatex
readme/Rules.scalatex
scalafix-core/shared/src/main/scala/scalafix/internal/patch/ReplaceSymbolOps.scala
scalafix-core/shared/src/main/scala/scalafix/rewrite/package.scala
scalafix-tests/input/src/main/scala/test/ReplaceSymbol.scala

Close remaining issues in 0.5.0 milestone

---

readme/Installation.scalatex
readme/Rules.scalatex

Tested on ScalafixPlugin, works like a charm.

Add installation instructions to run sbtfix on plugin sources.

---

CONTRIBUTING.md
scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test

I have implemented two tasks mentioned in #349 
I'm not 100% happy with the implementation itself but it fits into my "good enough" category. Let me know what to improve :)
I have modified the only sbt test that was present but I can put this logic into a separate one. Let me know whats your preference.

Introduce scalafixTest and sbtfixTest sbt tasks

---

readme/Rules.scalatex
scalafix-core/shared/src/main/scala/scalafix/internal/config/DisableConfig.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala
scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixRuleNames.scala
scalafix-tests/input/src/main/scala/test/Disable.scala

Rename Disable to DisableSymbol

---

scalafix-reflect/src/main/scala/scalafix/internal/reflect/ScalafixToolbox.scala

When coursier created a standalone executable for Scalafix, then the app
is run in an unusual classloader. The thing is a URLClassLoader, but
urls of the individual jars are  weird - their getProtocol is not file,
but bootstrapsomethingsomething, and their getPath doesn't point to
anything on the file system.
This is not at all a problem for running Scalafix, but it becomes an
issue when Scalafix is doing runtime compilation to load rules using
the file: protocol. The Scala compiler instance that's spun up for
runtime compilation doesn't understand those weird urls, so compilation
fails.
The proposed patch fixes the compilation failure by extracting the jars
into temporary files on disk, and then passing paths to those files to
the Scala compiler instance.

handle coursier's --standalone classloader

---

build.sbt
scalafix-core/shared/src/main/scala/scalafix/util/TokenClasses.scala

Should unblock unidoc setup in #386

Remove dependency on scalamacros/paradise

---

project/Mima.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala
scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala

Issue https://github.com/scalacenter/scalafix/issues/344

Replaced Tokens with Seq[Token]

---

project/plugins.sbt

In relation to https://github.com/scalacenter/scalafix/issues/281

Updated sbt-scalajs-bundler version

---

website/src/main/tut/docs/users/faq.md

Document alternatives

---

build.sbt
project/ScalafixBuild.scala
scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixEnable.scala
scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/project/build.properties
scalafix-sbt/src/sbt-test/sbt-scalafix/scalafixEnable/build.sbt
scalafix-sbt/src/sbt-test/sbt-scalafix/scalafixEnable/project/plugins.sbt
scalafix-sbt/src/sbt-test/sbt-scalafix/scalafixEnable/project/project/plugins.sbt
scalafix-sbt/src/sbt-test/sbt-scalafix/scalafixEnable/test
website/src/main/tut/docs/users/installation.md

New `scalafixEnable` command and (hopefully) clearer docs.

Simplify sbt-scalafix installation

---

website/src/main/tut/docs/users/installation.md

Add a chapter to get scalafix running with a scala-maven-plugin based project;

Add documentation to use with maven

---

build.sbt
project/ScalafixBuild.scala

We are block by Support sbt 1 in semanticdb-scalac:
https://github.com/scalameta/scalameta/issues/1157

Disable sbt 1.0 (fix #447)

---

CONTRIBUTING.md

I'm trying to understand what went wrong in https://github.com/scalacenter/scalafix/issues/468 I'm documenting how travis was setup on this repository to release on new tag.

Add documentation on how the publish setup is configured

---

project/ScalafixBuild.scala

for some reason sbt is not picking up `globalSettings`

Move globalSettings to projectSettings (fix #468)

---

project/ScalafixBuild.scala

https://github.com/scalacenter/scalafix/issues/468 take 2

Move only scmInfo and publishTo to projectSetting

---

scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/DottyKeywords.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/DottyVarArgPattern.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/DottyVolatileLazyVal.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitUnit.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoAutoTupling.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoInfer.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoValInForComprehension.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedImports.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedTerms.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveXmlLiterals.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/Sbt1.scala
scalafix-core/shared/src/main/scala/scalafix/rule/Rule.scala
scalafix-core/shared/src/main/scala/scalafix/rule/ScalafixRules.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ScalafixReflectTests.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ToolClasspathTests.scala

Closes #260 
This is my first contribution to scalafix, so huge amounts of feedback are welcome!

Add descriptions to rules

---

scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitDiff.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala

also add positive test for --diff-base

Drop-in detect wrong hash and missing commits (fix #483)

---

scalafix-core/shared/src/main/scala/scalafix/internal/rule/DottyAutoTuplingFunctionArgs.scala
scalafix-core/shared/src/main/scala/scalafix/rule/ScalafixRules.scala
scalafix-tests/input/src/main/scala/test/DottyAutoTuplingFunctionArgs.scala
scalafix-tests/output-dotty/src/main/scala/test/DottyAutoTuplingFunctionArgs.scala
website/src/main/resources/microsite/data/rules.yml
website/src/main/tut/docs/rules/DottyAutoTuplingFunctionArgs.md

http://dotty.epfl.ch/docs/reference/auto-parameter-tupling.html
@olafurpg, is this something you would like to have in scalafix at this point?

Add rule to leverage automatic tupling of function parameters in Dotty

---

website/src/main/tut/docs/rules/DottyAutoTuplingFunctionArgs.md

Link to #521 in docs. Review @marcelocenerine

Add caveats to DottyAutoTuplingFunctionArgs docs

---

scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala

Thanks @MasseGuillaume for reporting in https://github.com/scalacenter/scalafix/issues/264#issuecomment-353380824

Remove dead comment

---

scalafix-core/shared/src/main/scala/scalafix/util/TokenList.scala

Followup for #517 
Review @marcelocenerine

Add docstring explaning next/prev special behavior.

---

scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixJarFetcher.scala
website/src/main/tut/docs/users/installation.md

I manually tested this and found a bug related to fetching snapshot releases through sbt-scalafix, which should be fixed in this PR as well.

Snapshot installation instructions

---

website/src/main/tut/docs/users/installation.md

Fixes #573 Double checked locally that it works

Fix rendering of sbt "settings and tasks"

---

.scalafmt.conf
build.sbt
scalafix-cli/src/main/scala/scalafix/cli/Cli.scala
scalafix-sbt/src/main/scala/sbt/scalafixsbt/JLineAccess.scala
scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala
scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixRuleNames.scala
scalafix-sbt/src/test/scala/scalafix/internal/sbt/ScalafixCompletionsTest.scala

https://github.com/scalacenter/scalafix/issues/260

Add completion for rules description in sbt.

---

website/src/main/tut/docs/users/installation.md

This PR should fix the vertical alignments of comments in the web view.

Fix vertical alignment of comments

---

project/Dependencies.scala

This should hopefully fix the flaky test suite

Upgrade to Scalameta v3.7.3

---

scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala

 Add scalafixMetacpCacheDir setting in sbt-scalafix

---

scalafix-tests/input/src/main/scala/test/DisableRegex.scala
scalafix-tests/input/src/main/scala/test/DisableSimple.scala

Tests for new behavior on Term.Select in Disable rule

---

website/src/main/tut/docs/users/configuration.md

Disable.null -> DisableSyntax.keywords.null

---

scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala

Make Patch.merge public.

---

scalafix-core/shared/src/main/scala/scalafix/internal/util/PrettyType.scala

Don't include final modifier for objects.

---

scalafix-core/shared/src/main/scala/scalafix/internal/config/DisableSyntaxConfig.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxBase.scala
scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxNoValPatterns.scala

Done on the Open Source Spree for flatMap(Oslo) 2018.

Add syntactic rule for matching on assignment #716

---

scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedTerms.scala
scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixRuleNames.scala
scalafix-tests/input/src/main/scala/test/RemoveUnusedTerms.scala
scalafix-tests/output/src/main/scala/test/RemoveUnusedTerms.scala

Attempt to fix https://github.com/scalacenter/scalafix/issues/626

Fix RemoveUnusedTerms for private defs

---

scalafix-core/shared/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
scalafix-tests/input/src/main/scala/test/escapeHatch/AnchorDescription.scala
scalafix-tests/input/src/main/scala/test/escapeHatch/AnchorUnused.scala
website/src/main/tut/docs/users/configuration.md

Allow arbitrary description in scalafix:on|off|ok comments

---

build.sbt
project/Dependencies.scala
project/plugins.sbt
project/project/plugins.sbt

This required upgrading
- sbt-scalajs
- sbt-scalafix

Upgrade to 2.12.6

---

scalafix-cli/src/main/scala/scalafix/cli/Cli.scala

Add scalafix.cli.Cli back

---

scalafix-core/shared/src/main/scala/scalafix/internal/config/DisableConfig.scala
scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala
scalafix-tests/input/src/main/scala/test/DisableRegex.scala
scalafix-tests/input/src/main/scala/test/DisableUnlessInside.scala

This is an attempt to fix #707
@fommil

707: Disable.unlessInside safeBlock array

---

scalafix-tests/input/src/main/scala/test/escapeHatch/AnnotationFullyQualified.scala
scalafix-tests/input/src/main/scala/test/escapeHatch/AnnotationMultipleRules.scala
scalafix-tests/input/src/main/scala/test/escapeHatch/AnnotationPrefixedRules.scala
scalafix-tests/input/src/main/scala/test/escapeHatch/AnnotationUnused.scala

Fix tests containing multiple @SuppressWarnings annotation on a single element

---

.travis.yml
project/ScalafixBuild.scala

- disable coverage, it's more noisy than helpful IMO
- remove obsolete ci-release command

Build changes

---

scalafix-cli/src/main/scala/scalafix/internal/v1/ArgExpansion.scala
scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSyntacticSuite.scala

Fixes https://github.com/scalacenter/scalafix/issues/794

Support expansion of cli args through a file

---

docs/rule-authors/tutorial.md
docs/rules/RemoveUnused.md
scalafix-core/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
scalafix-docs/src/main/scala/docs/website.scala
scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnusedConfig.scala
scalafix-tests/input/src/main/scala/test/RemoveUnusedImports.scala
scalafix-tests/output/src/main/scala-2.12/test/RemoveUnusedImportsTrailingCommas.scala
scalafix-tests/output/src/main/scala/test/RemoveUnusedImports.scala
scalafix-tests/output/src/main/scala/test/RemoveUnusedImportsCommas.scala
website/i18n/en.json
website/sidebars.json

I ran the rule on akka and found a couple low hanging fruit improvements.

Polish remove unused rule based on real-world experiment

---

docs/users/installation.md

Related to: https://github.com/scalacenter/sbt-scalafix/pull/22

One task to rule them all: scalafix

---

website/core/Footer.js
website/pages/en/index.js
website/static/css/custom.css

Replace lorm ipsum on landing page

---

project/Dependencies.scala

This fixes a bug with handling of repeated cli arguments.

Upgrade to metaconfig v0.8.4

---

docs/developers/sharing-rules.md
docs/developers/tutorial.md
docs/users/installation.md

Usefull when using from project/Build.scala

Add fully qualified name for scalafixDependencies

---

docs/developers/semantic-tree.md
docs/users/installation.md
scalafix-core/src/main/scala/scalafix/internal/util/Pretty.scala
scalafix-core/src/main/scala/scalafix/internal/v1/DocumentFromProtobuf.scala
scalafix-core/src/main/scala/scalafix/internal/v1/InternalSemanticDoc.scala
scalafix-core/src/main/scala/scalafix/internal/v1/SymtabFromProtobuf.scala
scalafix-core/src/main/scala/scalafix/v1/SemanticTree.scala
scalafix-core/src/main/scala/scalafix/v1/SemanticType.scala
scalafix-core/src/main/scala/scalafix/v1/Signature.scala
scalafix-core/src/main/scala/scalafix/v1/package.scala
scalafix-docs/src/main/scala/docs/FileModifier.scala
scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala
scalafix-tests/unit/src/main/resources/expect/Pretty.expect

Live demo: https://olafurpg.github.io/scalafix/docs/developers/semantic-tree.html (may take a few minutes to sync)

Add "Cookbook" section for how to use semantic trees

---

docs/users/installation.md
project/Dependencies.scala
scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
scalafix-cli/src/main/scala/scalafix/internal/v1/ValidatedArgs.scala
scalafix-core/src/main/scala/scalafix/internal/config/FilterMatcher.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala

Respect -P:semanticdb:exclude and document further how to exclude files

---

scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntaxConfig.scala

Add example value for noUniversalEqualityMessage

---

docs/users/installation.md

Fixed typo

---

build.sbt
scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
scalafix-core/src/main/scala/scalafix/internal/patch/PatchInternals.scala
scalafix-docs/src/main/scala/docs/FileModifier.scala
scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala
scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala
scalafix-tests/unit/src/test/scala-2.12/scalafix/tests/cli/ScalafixImplSuite.scala

Made the changes necessary to get this building on my system. Currently 20 of the tests fail, as opposed to 40 without the fix. I've attached the tests log below. It looks like a lot of the failures have to do with scalameta, but I don't have time at the moment to look into what's going wrong. It may end up that scalameta will have to have fixes applied before everything work.
[tests.txt](https://github.com/scalacenter/scalafix/files/2405289/tests.txt)

Java 11 compat

---

docs/developers/semantic-type.md
docs/developers/symbol-information.md
scalafix-core/src/main/scala/scalafix/internal/util/Pretty.scala
scalafix-core/src/main/scala/scalafix/v1/SymbolInformation.scala
scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala

Live demo: https://olafurpg.github.io/scalafix/docs/developers/symbol-information.html

Update docs for SymbolInformation and SemanticType

---

docs/developers/patch.md
docs/developers/semantic-tree.md
docs/developers/semantic-type.md
docs/developers/symbol-information.md
docs/developers/symbol-matcher.md
website/siteConfig.js

Discussion https://github.com/scalameta/mbrowse/pull/104

Rename mbrowse to metabrowse

---

scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntaxConfig.scala
scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxBase.scala

Add DisableSyntax.noWhileLoops option

---

docs/developers/tutorial.md

Reported via gitter https://gitter.im/scalacenter/scalafix?at=5bd8cac01c100a4f290c6473
Thanks @amarrella!

Fix command-line example for custom rules

---

.jvmopts
.travis.yml
build.sbt
scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
scalafix-core/src/main/scala/scalafix/internal/patch/PatchInternals.scala
scalafix-core/src/main/scala/scalafix/internal/v1/FingerprintOps.scala
scalafix-docs/src/main/scala/docs/FileModifier.scala
scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala
scalafix-reflect/src/main/scala/scalafix/internal/reflect/RuleDecoderOps.scala
scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala
scalafix-tests/unit/src/test/scala-2.12/scalafix/tests/cli/ScalafixImplSuite.scala

This was enabled by the upgrade to Scalameta v4.1.0.
Fixes #880

Add support for Java 11

---

README.md

Thank you for having me here, guys! I was thrilled to witness how the
project got better and better over time, and I am excited to see
what roads you'll be taking next.

Goodbye, Scalafix!

---

docs/rules/external-rules.md
docs/rules/overview.md
website/sidebars.json

Document how to use external rules in User guide

---

scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala

This PR enables scalafix-cli to run `--help`, `--version`, `--bash`, `--zsh` options without the validation, and fixes https://github.com/scalacenter/scalafix/issues/957 and https://github.com/scalacenter/scalafix/issues/933
Here's the result of `./scalafix --version` on the `scalacenter/scalafix` with scalafix 0.9.6
```
$ ./scalafix --version
warning: Name RemoveUnusedImports is deprecated. Use RemoveUnused
instead (since 0.6.0)
warning: Name RemoveUnusedTerms is deprecated. Use RemoveUnused instead
(since 0.6.0)
error: 2 errors
[E0] The Scala compiler option "-Ywarn-unused" is required to use
RemoveUnused.
To fix this problem, update your build to use at least one Scala
compiler
option that starts with "-Ywarn-unused"
[E1] The Scala compiler option "-Ywarn-unused" is required to use …
```

Enable to run `--help` and `--version` option without validation

---

docs/rules/ExplicitResultTypes.md
docs/rules/NoAutoTupling.md
docs/rules/RemoveUnused.md
docs/users/installation.md
project/Dependencies.scala
project/ScalafixBuild.scala
scalafix-docs/src/main/scala/docs/Main.scala
scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala

Clarify docs about Scala support

---

scalafix-core/src/main/scala/scala/meta/internal/scalafix/ScalafixScalametaHacks.scala
scalafix-core/src/main/scala/scalafix/internal/util/SymbolOps.scala
scalafix-tests/shared/src/main/scala/test/SymbolTest.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/v1/SymbolSuite.scala

Quote names when necessary in Symbol#normalized

---

docs/users/installation.md

Mainly to advertize https://github.com/scalacenter/sbt-scalafix/pull/102

update doc about sbt-scalafix tasks/settings (as of 0.9.16)

---

CONTRIBUTING.md

The goal is to avoid detached commit.

Improve release documentation

---

.scala-steward.conf

As discussed on [gitter](https://gitter.im/scalacenter/scalafix?at=5ee3598acf270066f3cd1ada)

bi-weekly scala steward updates to reduce noise

---

docs/users/installation.md

Companion PR of https://github.com/scalacenter/sbt-scalafix/pull/140

document scalafixOnCompile

---

README.md
project/ScalafixBuild.scala

My personal life has changed considerably (and twice) over the last +2 years. Parenting is fun and rewarding, but free time becomes scarce. As a result, I haven't made any contribution to the project for almost 2 years 😱 . I think it's time to say goodbye to Scalafix and to the people who I've had the opportunity to interact with for ~1 year. Special thanks to @olafurpg for the invitation and for all the Scala tips in my PRs. I hope we can meet one day in some Scala conference once this pandemic is over. Best of luck to you all 👋

Goodbye from Marcelo Cenerino

---

.gitignore
scalafix-core/src/main/scala/scalafix/internal/patch/PatchInternals.scala
scalafix-core/src/main/scala/scalafix/patch/Patch.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/core/PatchSuite.scala

- Patch.around could be useful when show implicit conversions

add a new method to Patch Api

---

.scalafmt.conf

Missed in https://github.com/scalacenter/scalafix/pull/1136

fix path to scalafmt binary

---

.github/workflows/ci.yml
scalafix-tests/unit/src/test/scala/scalafix/tests/config/ArgsSuite.scala

https://github.com/scalacenter/scalafix/pull/1279/files#r521892504

enforce scalafix across configurations

---

docs/rules/community-rules.md
website/sidebars.json

bootstrap a community page

---

README.md

This reverts commit 8364b048893e3918dbdb2b9da8fb9b24136ac714.

Revert "add a badge"

---

scalafix-core/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
scalafix-core/src/main/scala/scalafix/internal/patch/PatchInternals.scala

Avoids stack overflows when processing large `Concat` structures by using trampolining.

Trampoline Concat patches.

---

scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala

I think having a default value is better than None.

Make dialect not an option

---

docs/users/installation.md

Companion of https://github.com/scalacenter/sbt-scalafix/pull/213

reflect new scalafixCaching default

---

.scalafix.conf
bin/test-release.sh
project/Dependencies.scala
project/ScalafixBuild.scala

Also fix the MiMa regression https://github.com/scalacenter/scalafix/pull/1370#issuecomment-820461009

scala 2.13.6

---

project/Mima.scala
scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
scalafix-core/src/main/scala/scalafix/internal/config/ScalaVersion.scala
scalafix-core/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
scalafix-reflect/src/main/scala/scalafix/internal/reflect/RuleInstrumentation.scala
scalafix-testkit/src/main/scala/scalafix/testkit/AbstractSemanticRuleSuite.scala
scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala

https://github.com/scalameta/scalameta/issues/2323

support parsing scala 2.13.6 / 2.12.14 -Xsource:3 dialect

---

docs/developers/setup.md

https://github.com/scalacenter/scalafix.g8/pull/19

Docs update for Scala 3 support in scalafix.g8 template

---

project/Dependencies.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/core/PatchSuite.scala

https://github.com/scalameta/scalameta/issues/2364

bump scalameta to fix regression for replaceTree(Template, t.syntax)

---

build.sbt
project/Dependencies.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/config/DisableSyntaxConfigSuite.scala

Highlights
- https://github.com/scalameta/metaconfig/pull/131
- https://github.com/scalameta/metaconfig/pull/132

metaconfig 0.9.14

---

.github/dependabot.yml

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

ask dependabot to upgrade github actions

---

docs/rules/ProcedureSyntax.md
scalafix-rules/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala
scalafix-tests/input/src/main/scala-2/test/procedureSyntax/ConstructorProcedureSyntax.scala
scalafix-tests/input/src/main/scala-2/test/procedureSyntax/ExplicitUnit.scala
scalafix-tests/input/src/main/scala-2/test/procedureSyntax/ProcedureSyntax.scala
scalafix-tests/output/src/main/scala-2/test/procedureSyntax/ConstructorProcedureSyntax.scala
scalafix-tests/output/src/main/scala-2/test/procedureSyntax/ExplicitUnit.scala
scalafix-tests/output/src/main/scala-2/test/procedureSyntax/ProcedureSyntax.scala

Procedure syntax

---

docs/developers/local-rules.md
docs/developers/sharing-rules.md
docs/developers/tutorial.md
docs/rules/external-rules.md
docs/users/installation.md

Companion for https://github.com/scalacenter/sbt-scalafix/pull/225

docs: sbt-scalafix is now only published for sbt 1.x

---

project/Dependencies.scala

Attempt at fixing https://github.com/scalacenter/scalafix/issues/1510

bump coursier

---

.github/workflows/deploy-website.yml

Update checkout github action

---

website/sidebars.json

Follows https://github.com/scalacenter/scalafix/pull/1496

docs: add new rule and reorder alphabetically in sidebar

---

CONTRIBUTING.md

Follows https://github.com/scalacenter/scalafix/commit/91551070a92033ad18395ef718983d25834dda47
Enforcement is currently pending https://github.com/scalacenter/scalafix/pull/1568#issuecomment-1092188919

docs: we use MiMa indirectly now

---

bin/test-release.sh
project/Dependencies.scala
project/ScalafixBuild.scala

Closes https://github.com/scalacenter/scalafix/issues/1614

scala 2.12.16

---

docs/rules/community-rules.md

https://github.com/xuwei-k/replace-symbol-literals/commit/303f8112e0849d818ac985a991c895e11d564d9f

xuwei-k/replace-symbol-literals is now in xuwei-k/scalafix-rules

---

build.sbt
project/ScalafixBuild.scala

https://github.com/dwijnand/sbt-project-graph

build (java) interfaces module once for all scala versions

---

scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala

That was the original intent of https://github.com/scalacenter/scalafix/pull/1633, but [example-scalafix-rule does not use metaconfig](https://github.com/scalacenter/example-scalafix-rule/search?q=metaconfig).

cli should support configurable rules built against older core

---

README.md

Follows https://github.com/scalacenter/scalafix/pull/1653

remote gitter shield

---

docs/developers/tutorial.md

Documentation for https://github.com/scalacenter/scalafix-named-literal-arguments/pull/9

Update tutorial for rule suppression examples

---

docs/users/installation.md

Follows https://github.com/scalacenter/scalafix/pull/1729

docs: add note about final 2.11 version

---

docs/developers/patch.md
docs/developers/symbol-matcher.md
project/Dependencies.scala
project/ScalafixBuild.scala

Closes https://github.com/scalacenter/scalafix/issues/1770

Scala 2.12.18 & 2.13.11

---

project/ScalafixBuild.scala

See https://github.com/lampepfl/dotty/pull/10746. Note that https://github.com/sbt/sbt/issues/6817 is somewhat limiting the effect of that.

Move to safer compatibility flag for javac

---

LICENSE.md

Closes https://github.com/scalacenter/scalafix/issues/1831

Use BSD-3 license template from GitHub

---

scalafix-core/src/main/scala/scalafix/internal/util/SymbolOps.scala
scalafix-tests/integration/src/test/scala/scalafix/tests/v1/SymbolMatcherSuite.scala

Fixes https://github.com/scalacenter/scalafix/issues/1880

better support of backquoted identifiers in SymbolMatcher

---

website/sidebars.json

- https://github.com/scalacenter/scalafix/pull/1939
- https://github.com/scalacenter/scalafix/blob/112fd902227a9a90351af66761777997a9c793ba/docs/developers/local-rules.html#L229
- https://scalacenter.github.io/scalafix/docs/developers/local-rules.html

docs: remove dead link for `cross-publish-custom-rules`

---

build.sbt

Leverage https://github.com/sbt/sbt-projectmatrix/pull/89

don't use projectmatrix on interfaces as it's not cross-built

---

docs/users/installation.md

Complements https://github.com/scalacenter/scalafix/pull/1975

docs: clarify that resolvers is only looked up at build level

---

bin/test-release.sh
project/Dependencies.scala
project/ScalafixBuild.scala
scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala

https://github.com/scalacenter/scalafix/issues/1983

build and test against Scala 2.13.14

---

docs/rules/RemoveUnused.md
docs/users/installation.md
scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala

Follows https://github.com/scalacenter/scalafix/pull/1728

improve docs about RemoveUnused

---

CONTRIBUTING.md
docs/developers/local-rules.md
docs/developers/setup.md
docs/developers/tutorial.md
docs/users/installation.md
project/ScalafixBuild.scala
scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala

https://github.com/sbt/sbt/pull/6309
Follows https://github.com/scalacenter/scalafix/pull/1417

docs: use slash syntax for sbt

---

docs/users/installation.md
scalafix-docs/src/main/scala/docs/Main.scala

document tested support for Scala3 LTS & Scala3 Next

---

project/ScalafixBuild.scala
project/plugins.sbt

Tests https://github.com/scalacenter/scalafix/issues/1680

use cli_3.x.y to inspect Scala 3 sources

---

scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
scalafix-tests/integration/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
scalafix-tests/integration/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala

Follows https://github.com/scalacenter/scalafix/pull/2034 which increased race conditions and thus flakiness
Two first commits are just unrelated minor fixes discovered during troubleshooting

Fix flaky integration tests

---

scalafix-core/src/main/scala/scalafix/v1/SymbolInformation.scala

https://github.com/scalameta/scalameta/pull/2439

expose Scala 3 modifiers

---

docs/rules/community-rules.md

Add dedis/scapegoat-scalafix

---

docs/users/installation.md

Companion for https://github.com/scalacenter/sbt-scalafix/pull/412

docs: drop sbt 1.3.x support

---

docs/rules/RemoveUnused.md

Follows https://github.com/scalacenter/scalafix/pull/2052

RemoveUnused: document 2.13.15 patvars behavior

---

bin/test-release.sh
project/Dependencies.scala

It's live already https://github.com/scala/scala3/issues/21644 !

build and test against Scala 3.3.4 final

---

docs/users/configuration.md

https://github.com/scalacenter/scalafix/pull/2062/files#r1787309735

docs: tweak syntax to be shell-compliant

---

scalafix-core/src/main/scala/scalafix/internal/config/ScalaVersion.scala
scalafix-tests/unit/src/test/scala/scalafix/tests/config/ScalaVersionSuite.scala

Closes https://github.com/scalacenter/scalafix/issues/2107

don't reject Scala 2 nightlies for community build

---

.github/workflows/ci.yml
.github/workflows/deploy-website.yml
.github/workflows/release.yml

https://github.com/actions/runner-images/issues/10767

ubuntu-latest now points to 24.04 which does not include sbt

---

scalafix-tests/input/src/main/scala-3next/test/explicitResultTypes/Scala3_6OrGreater.scala
scalafix-tests/output/src/main/scala-3next/test/explicitResultTypes/Scala3_6OrGreater.scala

more SIP-64 tests

---

project/Dependencies.scala

https://github.com/scalameta/scalameta/releases/tag/v4.13.4
Fixes https://github.com/scalacenter/scalafix/issues/2209 thanks to https://github.com/scalameta/scalameta/pull/4215

scalameta 4.13.4

---

docs/developers/local-rules.md

As tested in https://github.com/scalacenter/sbt-scalafix/pull/481, although only partially: usage of `scalafix-testkit` (published for 3.x since https://github.com/scalacenter/scalafix/pull/2034) in combination with local rules is not.
As snippets get bigger, I am switching to scala snippets rather than diff ones to help readability.

document support for local rules written in Scala 3

---

.scala-steward.conf

Helps with https://github.com/scalacenter/scalafix/issues/1146

upgrade sbt-scalafix as soon as it's out

---

scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala

https://discord.com/channels/632642981228314653/632683673417678860/1370322868847513660

scala version is used to infer dialect so it's a common opt

---

docs/rules/RemoveUnused.md
scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala
scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala

Was implemented in the scala3 compiler with this issue
https://github.com/scala/scala3/issues/18559

Add -Wall as supported flag for RemoveUnused

---

bin/test-release.sh
docs/developers/tutorial.md
docs/users/installation.md
project/ScalafixBuild.scala
scalafix-rules/src/main/scala-3/pc/Embedded.scala
scalafix-tests/integration/src/test/scala-2/scalafix/tests/util/compat/SemanticdbPlugin.scala
scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala

Follows https://github.com/scalacenter/scalafix/pull/2257

use Sonatype Central Snapshots instead of OSSRH public/snapshots
