scalacenter/scalafix

- .drone.yml
- build.sbt
- cli/src/main/scala/scalafix/cli/Cli.scala
- core/src/main/scala/scalafix/ScalafixConfig.scala
- core/src/main/scala/scalafix/Versions.scala
- core/src/test/resources/ExplicitImplicit/basic.source
- project/build.sbt
- project/plugins.sbt
- readme/Installation.scalatex
- readme/Readme.scalatex
- scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscComponent.scala
- scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscPlugin.scala
- scalafix-nsc/src/test/scala/scalafix/DiffTest.scala
- scalafix-nsc/src/test/scala/scalafix/SemanticTests.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/.scalafix.conf
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/build.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/p2/src/test/scala/Test.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/project/build.properties
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/src/main/java/Test.java
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/src/main/scala/Test.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/basic/src/test/scala/Test.scala
- scalafix-tests/src/test/scala/scalafix/tests/IntegrationPropertyTest.scala
My experience from scalafmt is that the configuration quickly grows and using a robust configuration from the start is useful. I went with HOCON because
- HOCON appears to be the least controversial choice in the Scala community
- I can automatically read HOCON into a case class using metaconfig from scalafmt (not implemented yet since config class is small)
> Support hocon configuration.

- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- removing unused dependencies injected by sbt plugins (e.g. DocTest).
This prevents errors when using the sbt plugin on projects like
refined.
- avoid unnecessary downloads on scalafix-nsc dependencies, since it's
published as a fat jar.
> Exclude unused deps in sbt plugin

- build.sbt
- core/src/main/scala/scalafix/rewrite/ExplicitImplicit.scala
- core/src/main/scala/scalafix/rewrite/Rewrite.scala
- core/src/main/scala/scalafix/rewrite/Xor2Either.scala
- core/src/main/scala/scalafix/syntax/package.scala
- core/src/main/scala/scalafix/util/OrganizeImports.scala
- core/src/main/scala/scalafix/util/Patch.scala
- core/src/main/scala/scalafix/util/Replacer.scala
- core/src/main/scala/scalafix/util/TreeExtractors.scala
- project/Build.scala
- scalafix-nsc/src/main/scala/scalafix/nsc/NscScalafixMirror.scala
- scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscComponent.scala
- scalafix-nsc/src/main/scala/scalafix/nsc/ScalafixNscPlugin.scala
- scalafix-nsc/src/test/resources/syntactic/Xor2Either.source
- scalafix-nsc/src/test/scala/cats/data/Xor.scala
- scalafix-nsc/src/test/scala/cats/implicits.scala
- scalafix-nsc/src/test/scala/scalafix/SemanticTests.scala
- scalafix-tests/src/test/scala/scalafix/tests/IntegrationPropertyTest.scala
- scalafix-tests/src/test/scala/scalafix/tests/ItTest.scala
This PR integrates the scala.meta mirror even more tightly into scalafix. It includes an example Xor2Either rewrite using the Symbol/Signature API.
cc/ #29 @ShaneDelmore
> Experimenting with scala.meta mirror

- cli/src/main/scala/scalafix/cli/ArgParserImplicits.scala
- cli/src/main/scala/scalafix/cli/Cli.scala
- core/src/main/scala/scalafix/Failure.scala
- core/src/main/scala/scalafix/Scalafix.scala
- core/src/main/scala/scalafix/ScalafixConfig.scala
- core/src/main/scala/scalafix/rewrite/ExplicitImplicit.scala
- core/src/main/scala/scalafix/rewrite/ProcedureSyntax.scala
- core/src/main/scala/scalafix/rewrite/Rewrite.scala
- core/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- core/src/main/scala/scalafix/rewrite/ScalafixMirror.scala
- core/src/main/scala/scalafix/rewrite/VolatileLazyVal.scala
- core/src/main/scala/scalafix/rewrite/Xor2Either.scala
- core/src/main/scala/scalafix/rewrite/package.scala
- core/src/main/scala/scalafix/syntax/package.scala
- core/src/main/scala/scalafix/util/CanonicalImport.scala
- core/src/main/scala/scalafix/util/OrganizeImports.scala
- core/src/main/scala/scalafix/util/Patch.scala
- core/src/main/scala/scalafix/util/Replacer.scala
- scalafix-nsc/src/test/scala/scalafix/ImportPatches.sc
- scalafix-nsc/src/test/scala/scalafix/SemanticTests.scala
- scalafix-nsc/src/test/scala/scalafix/rewrite/ErrorSuite.scala
- scalafix-nsc/src/test/scala/scalafix/rewrite/RewriteSuite.scala
- scalafix-tests/src/test/scala/scalafix/tests/ItTest.scala
Rewrite now accepts a type parameter. Why?
- Principle of least power, if you don't need semantic information,
don't require it.
- Rewrite requirements are documented in the type.
- Possible to construct RewriteCtx from scala.meta.Mirror.
- Paves to way to contribute Rewrite upstream to scala.meta
> Refactor rewrite api.

- cli/src/main/scala/scalafix/cli/ArgParserImplicits.scala
- cli/src/main/scala/scalafix/cli/Cli.scala
- core/src/main/scala/scalafix/ScalafixConfig.scala
- core/src/main/scala/scalafix/rewrite/ExplicitImplicit.scala
- core/src/main/scala/scalafix/rewrite/ProcedureSyntax.scala
- core/src/main/scala/scalafix/rewrite/Rewrite.scala
- core/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- core/src/main/scala/scalafix/rewrite/VolatileLazyVal.scala
- core/src/main/scala/scalafix/rewrite/Xor2Either.scala
- core/src/main/scala/scalafix/rewrite/package.scala
- core/src/main/scala/scalafix/util/TokenList.scala
- scalafix-nsc/src/test/scala/scalafix/rewrite/ErrorSuite.scala
- scalafix-tests/src/test/scala/scalafix/tests/ItTest.scala
This change gives the following nice properties
RewriteCtx[ScalafixMirror] <: RewriteCtx[Mirror]
Rewrite[ScalafixMirror] <: RewriteCtx[Any]
This also allows rewrites to be defined as case objects extending
Rewrite[A] where A is the least powerful api needed for this rewrite.
> Make RewriteCtx covariant and Rewrite contravariant.

- core/src/main/scala/scalafix/Scalafix.scala
- core/src/main/scala/scalafix/rewrite/package.scala
- core/src/main/scala/scalafix/util/CanOrganizeImports.scala
- core/src/main/scala/scalafix/util/CanonicalImport.scala
- core/src/main/scala/scalafix/util/OrganizeImports.scala
- core/src/main/scala/scalafix/util/Patch.scala
- core/src/main/scala/scalafix/util/Replacer.scala
This makes is possible to use OrganizeImports (without remove unused
imports) and Replacer with scala.meta.Mirror instead of ScalafixMirror.
> Replace ScalafixMirror with Mirror where possible.

- core/src/main/scala/scalafix/config/ScalafixMetaconfigReaders.scala
- core/src/main/scala/scalafix/rewrite/Rewrite.scala
- core/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- core/src/main/scala/scalafix/util/FileOps.scala
- core/src/main/scala/scalafix/util/Replacer.scala
- core/src/main/scala/scalafix/util/RewriteInstrumentation.scala
- core/src/main/scala/scalafix/util/ScalafixToolbox.scala
- rewrites/MyRewrite.scala
- rewrites/MyRewrite2.scala
- scalafix-nsc/src/test/resources/checkSyntax/FileRewrite.source
- scalafix-nsc/src/test/resources/checkSyntax/FileRewrite2.source
- scalafix-nsc/src/test/resources/checkSyntax/FqnRewrite.source
- scalafix-nsc/src/test/resources/checkSyntax/UrlRewrite.source
- scalafix-nsc/src/test/scala/scalafix/SemanticTests.scala
This commit adds support to load rewrites using different protocols
- `file:path/to/rewrite.scala`
- `https://github.com/...`
- `scala:fully.qualified.Name`
In the future, we can add support for other protocols like `scastie:snippet-hash`.
We use the scala.reflect toolbox to compile and load rewrites from code.
We instrument the code to make it compile with scala.reflect Toolbox.
> Support dynamic loading of rewrites from uri.

- cli/src/main/scala/scalafix/cli/Cli.scala
- cli/src/main/scala/scalafix/cli/ExitStatus.scala
- cli/src/test/scala/scalafix/cli/CliTest.scala
- core/src/main/scala/scalafix/Failure.scala
- core/src/main/scala/scalafix/Scalafix.scala
- core/src/main/scala/scalafix/rewrite/ScalafixMirror.scala
- Return proper exit codes on failure: parse/scalafix/unexpected error.
- Document exit code in --help.
- Clearer instruction on missing semantic api.
- Return Fixed.Failed on scalafix errors instead of throwing unexpected errors.
Fixes #104
> Clean up cli.

- cli/src/main/scala/scalafix/cli/Cli.scala
It turns out that one of the underlying reasons for #104 was that pants executes tools in a nailgun context, and in that case the exit code was being discarded.
> Set the exit code when running in a nailgun context

- scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala
- scalafix-tests/src/test/scala/scalafix/tests/GitHubUrlRewriteSuite.scala
Closes #125 
First working draft. I've setup some integration tests but they fail because the file referenced is not there. Not sure whether these tests make sense, or whether we should just unit test the shorthand expansion. Anyway, the `FileNotFound` exception shows a correct value, so 🎉.
@olafurpg take a look and let me know what you think!
> Add GitHub shorthand for URL rewrites

- scalafix-core/src/main/scala/scalafix/rewrite/ExplicitUnit.scala
- scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- scalafix-tests/src/test/resources/checkSyntax/ExplicitUnit.source
Closes #58 
It adds an explicit `Unit` return type to `def` declarations without a return type.
Example:
```diff
trait A {
-  def x
+  def x: Unit
}
```
> Add ExplicitUnit rewrite

- scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala
- scalafix-tests/src/test/scala/scalafix/tests/GitHubUrlRewriteSuite.scala
Closes #131 and also handles the case in which a repo name starts with a digit.
See unit tests, but in short
`some-repo` => `some_repo`
`42some-repo` => `_42some_repo`
Ugly but consistent (naming is hard)
> Safer derivation of package name from repo name

- scalafix-core/src/main/scala/scalafix/rewrite/NoAutoTupling.scala
- scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- scalafix-tests/src/test/resources/checkSyntax/NoAutoTupling.source
This is a first attempt at #66.
Trivial cases work fine, but it fails with multiple parameter lists since the tree is matched multiple times by `q"$fun(..$argss)"`.
E.g. when traversing the tree of `foo(1, 2)("a", "b")`, the pattern `q"$fun(..$argss)` matches
```scala
foo(1, 2)
```
and 
```scala
foo(1, 2)("a", "b")
```
so we end up with
```scala
foo(((1, 2)))(("a", "b"))
```
@olafurpg any hint to solve this?
> Add NoAutotupling semantic rewrite

- bin/new-rewrite.sh
- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/ScalafixOptions.scala
- scalafix-core/src/main/scala/scalafix/patch/ImportPatchOps.scala
- scalafix-core/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/src/main/scala/scalafix/rewrite/RemoveUnusedImports.scala
- scalafix-core/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- scalafix-core/src/main/scala/scalafix/syntax/package.scala
- scalafix-core/src/main/scala/scalafix/util/MatchingParens.scala
- scalafix-core/src/main/scala/scalafix/util/TokenClasses.scala
- scalafix-core/src/main/scala/scalafix/util/TokenList.scala
- scalafix-core/src/main/scala/scalafix/util/TokenOps.scala
- scalafix-core/src/main/scala/scalafix/util/TreeOps.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/Command.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedImports.scala
- scalafix-tests/integration/src/it/scala/scalafix/tests/ProjectTests.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedImports.scala
- scalafix-tests/output/src/main/scala/test/Xor2Either.scala
This rewrite does not group/sort/expand rewrites, only remove unused
imports. Supersedes #152
> Implement RemoveUnusedImports rewrite.

- build.sbt
- scalafix-core/src/main/scala/scalafix/rewrite/RemoveXmlLiterals.scala
- scalafix-tests/input/src/main/scala/test/RemoveXmlLiterals.scala
- scalafix-tests/output/src/main/scala/test/RemoveXmlLiterals.scala
We need to figure out how to rewrite:
```scala
e match { case <a>{_*}</a> => }
```
> Disable Xml Rewrite in pattern position

- readme/Testkit.scalatex
Currently the doc says:
```
addSbtPlugin("org.scalameta" % "sbt-scalahost" % 1.8.0)
```
This misses double quotations in version.
At open source spree at Copenhagen, I find this :)
> fix missing double quotations in scalafix-testkit doc

- readme/Testkit.scalatex
This fixes several points to make samples work.
* Remove dotty output directory from test case and add a note about it.
* Add scalafix configuration requirement in input source files.
* Add an explanation about output source files.
This PR is also made at open source spree at CPH. Thanks @olafurpg for guiding me. :)
> fix testkit sample to be workable

- build.sbt
- readme/Rewrites.scalatex
- scalafix-core/src/main/scala/scalafix/rewrite/DottyVarArgPattern.scala
- scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- scalafix-tests/input/src/main/scala/test/DottyVarArgPattern.scala
- scalafix-tests/output-dotty/src/main/scala/test/DottyVarArgPattern.scala
> Var-arg pattern (#59)

- scalafix-core/src/main/scala/scalafix/rewrite/NoAutoTupling.scala
- scalafix-tests/input/src/main/scala/test/NoAutoTupling.scala
- scalafix-tests/output/src/main/scala/test/NoAutoTupling.scala
Closes #147 
Still WIP, but the previously failing test cases are now green ✅ 
By the way, I just realized that maybe this whole rewrite can be a lot simpler if you use compiler messages.
Here's what scalac emits if the auto-tupling warning is on
```sg
[warn] /Users/gabro/buildo/scalafix/scalafix-tests/input/src/main/scala/test/NoAutoTupling.scala:15: Adapting argument list by creating a 2-tuple: this may not be what you want.
[warn]         signature: tup1.fooo(t: (Int, Int))(s: (String, String)): Int
[warn]   given arguments: 1, 2
[warn]  after adaptation: tup1.fooo((1, 2): (Int, Int))
[warn]     fooo(1, 2)("a", "b")
[warn]         ^
[warn] /Users/gabro/buildo/scalafix/scalafix-tests/input/src/main/scala/test/NoAutoTupling.scala:15: Adapting argument list by creating a 2-tuple: this may …
```
> Handle auto-tupling on functions

- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
This error was caused by a bad interplay between sbt-scalahost and
sbt-scalafix.
- sbt-scalahost injects stuff into both scalacOptions and
libraryDependencies.  In scalacOptions, we call update.value, which
relies on the existence of dependencies in libraryDependencies.
- sbt-scalafix creates a a synthetic project "scalafix-stub" to fetch
jars for scalafix-cli and sets the libraryDependencies to empty list
but leaves scalacOptions unchanged. scalafix-stub/compile
triggers scalafix-stub/scalacOptions which triggers
update.value to return an empty list.
This commit sets scalacOptions of scalafix-sbt to empty list, overriding
the injected scalacOptions by sbt-scalahost.
> Fix #200, override injected scalacOptions.

- readme/Faq.scalatex
- readme/ImplementingRewrites.scalatex
- readme/Readme.scalatex
- readme/Testkit.scalatex
- readme/src/main/scala/scalafix/Readme.scala
- scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/GitHubUrlRewriteSuite.scala
While writing the docs, I realized that there's a lot of boilerplate needed to setup a build correctly. I created https://github.com/scalacenter/scalafix.g8 and updated the `github:` protocol to make the two match.
> Update docs on how to implement rewrites

- bin/publish.sh
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/test/scala/scalafix/cli/AutoClasspathSuite.scala
- scalafix-cli/src/test/scala/scalafix/cli/CliTest.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRewriteSuite.scala
This setting will automatically find directories containing .semanticdb
files. This might be useful for example to run scalafix-cli from an sbt
multi-module build outside of an sbt session.
> Add support for --classpath=auto.

- scalafix-core/src/main/scala/scalafix/config/ExplicitReturnTypesConfig.scala
- scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala
- scalafix-tests/input/src/main/scala/test/ExplicitReturnTypes.scala
- scalafix-tests/output/src/main/scala/test/ExplicitReturnTypes.scala
This fixes #158 to add ExplicitReturnType with respecting configuration.
ATM memberKind and memberVisibility configuration supports are implemented in "AND" basis.
For example if you specify `[Val, Def]` for memberKind and `[Protected]` for memberVisibility, only `protected val` and `protected def`s are rewritten.
I believe it should be so, but please feel free to let me know if it's different from what you expect.
And I'm so sorry for making issue reference a bit dirty.
> Fix #158, fix ExplicitReturnType for non-implicits

- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/main/scala/scalafix/cli/ScalafixOptions.scala
- scalafix-cli/src/test/scala/scalafix/cli/CliTest.scala
- scalafix-core/src/main/scala/scalafix/config/RewriteKind.scala
- scalafix-core/src/main/scala/scalafix/config/ScalafixConfig.scala
- scalafix-core/src/main/scala/scalafix/config/ScalafixMetaconfigReaders.scala
- scalafix-core/src/main/scala/scalafix/config/package.scala
- scalafix-core/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/src/main/scala/scalafix/patch/Replacer.scala
- scalafix-core/src/main/scala/scalafix/rewrite/RemoveUnusedImports.scala
- scalafix-core/src/main/scala/scalafix/rewrite/Rewrite.scala
- scalafix-core/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- scalafix-core/src/main/scala/scalafix/syntax/package.scala
- scalafix-core/src/main/scala/scalafix/util/ClassloadRewrite.scala
- scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala
- scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixToolbox.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/DiffTest.scala
- scalafix-tests/integration/src/it/scala/scalafix/tests/URLConfiguration.scala
This commit refactors how mirrors are loaded in the cli. Before, mirrors
were eagerly loaded depending on whether --syntactic was passed or not.
This meant is was annoying to run syntactic rewrites, or you loaded
the semanticdb even if you didn't need it. After this commit, the cli
will only try to load the mirror if it's requested by a semantic
rewrite. This fix works for default rewrites along with
classloaded/compiled rewrites.
The most important change in this commit was to change `Option[Mirror]`
into `type LazyMirror = RewriteKind => Option[Mirror]`. This allowed
us to delay the computation of the mirror up to the point where we
needed to load the first semantic rewrite.
Along the way, I had to refactor a lot of things on the side, which
caused the large diff. The side changes are …
> Lazily compute mirror so auto-detect --syntactic.

- build.sbt
- scalafix-diff/js/src/main/scala/scalafix/diff/DiffUtils.scala
- scalafix-diff/jvm/src/main/scala/scalafix/diff/DiffUtils.scala
- scalafix-diff/shared/src/test/scala/scalafix/DiffUtilsSpec.scala
This adds a basic test for `DiffUtils.unifiedDiff` to ensure the output is consistent between JS and JVM implementations.
I found some discrepancies, namely:
> Add tests for scalafix-diff

- readme/ImplementingRewrites.scalatex
- scalafix-core/shared/src/main/scala/scalafix/package.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/ImportPatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/RewriteCtx.scala
This avoid the need for extension methods. The implementations of the
patch operations are now abstract to make it easier to read.
> Move patch operations into RewriteCtx, fixes #193.

- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/Cli.scala
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/main/scala/scalafix/internal/cli/ScalafixOptions.scala
- scalafix-cli/src/test/scala/scalafix/cli/CliTest.scala
- scalafix-core/shared/src/main/scala/scalafix/config/package.scala
- scalafix-core/shared/src/main/scala/scalafix/package.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/RemoveUnusedImports.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- scalafix-core/shared/src/main/scala/scalafix/syntax/package.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/DiffTest.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/IntegrationPropertyTest.scala
- scalafix-tests/shared/src/main/scala/cats/implicits.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/ErrorSuite.scala
I've been delaying this commit for too long hoping to fix it with
scalafix. However, it turns out that we can't yet use scalahost in the
scalafix repo because of https://github.com/scalameta/scalameta/issues/979.
I could not get myself to manually remove the imports so I implemented
instead an sbt plugin called sbt-messagehost that collects reported messages
from the compilerReporter in sbt and writes .semanticdb files. Using
messagehost, I was able to run RemoveUnusedImports on the scalafix
codebase. I suspect messagehost may become popular as a lightweight
alternative to scalahost.
I plan to publish messagehost later, it will not be part of the scalafix
repo.
> Remove unused imports.

- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/Cli.scala
- scalafix-cli/src/main/scala/scalafix/internal/cli/ScalafixOptions.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
This solution is kind of a hack. We statically generate the parser by
invoking scalafix-cli on every compilation of scalafix-sbt.
The benefit of this approach is that tab completions are always
generated in the same way in scalafix-cli.
> Generate tab completions for sbt, fixes #172.

- build.sbt
This library is necessary to patch broken .semanticdb files produced in
2.10.6.
> Add dependency on sbthost-runtime.

- bin/new-rewrite.sh
- project/plugins.sbt
- project/project/plugins.sbt
- scalafix-core/shared/src/main/scala/scalafix/config/MetaconfigPendingUpstream.scala
- scalafix-core/shared/src/main/scala/scalafix/config/PatchConfig.scala
- scalafix-core/shared/src/main/scala/scalafix/config/ScalafixMetaconfigReaders.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/patch/MoveSymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- scalafix-core/shared/src/main/scala/scalafix/syntax/package.scala
- scalafix-tests/input/src/main/scala/test/MoveSymbol.scala
- scalafix-tests/output/src/main/scala/com/geirsson/fastmath.scala
- scalafix-tests/output/src/main/scala/com/geirsson/mutable/CoolBuffer.scala
- scalafix-tests/output/src/main/scala/com/geirsson/mutable/unsafe/CoolMap.scala
- scalafix-tests/output/src/main/scala/test/MoveSymbol.scala
- scalafix-tests/output/src/main/scala/test/Xor2Either.scala
This patch can be used to move or rename call-sites of a global
definition like a class, trait, object or static def. This
implementation is crude, it is likely produce invalid code in many
cases. The patch tries to preserve the prefix when possible. For
example:
```
// config
from = a.b.c
to = d.b.x
// code before
import a.b.c
import a.b
b.c
c
// code after
import a.b
import d.b
import d.b.x
b.x
x
```
Room for improvement:
- Observe that `import a.b` is not removed as it may be used to prefix
other identifiers from the `a.b.` package. It should be possible to
remove the imports if its not used elsewhere.
- It's possible that duplicate imports are added, for example if
the source contains `import a.b_` then scalafix may still add
redundant `import a.b.c`.
- Imports are always inserted …
> Implement crude MoveSymbol patch.

- build.sbt
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/CliWrapperPlugin.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixJarFetcher.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
This removed the usage of synthetic projects in sbt-scalafix with
cours. I was trying out sbt-scalafix in the scalafix repo itself
and noticed that it didn't play nicely with with root build
auto-aggregation.
> Use coursier to fetch scalafix-cli jars.

- scalafix-core/shared/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/syntax/package.scala
- scalafix-tests/input/src/main/scala/test/MoveSymbol.scala
I also observed that we throw away the tail of symbols in Symbol.Multi.
This behavior does not make sense in normalize, instead it makes more
sense to normalize all the underlying symbols and provide another helper
to simplify Symbol.Multi.
> Normalize `package` in symbols.

- scalafix-core/shared/src/main/scala/scalafix/config/ScalafixConfig.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala
I find it a bit unsatisfying that rewrites must throw exceptions to
communicate errors in the configuration. Moreover, it's unnecessary
that the rewrite must validate the configuration on every RewriteCtx
instead of only once during construction. This fix is a short term
solution, we should eventually try to solve the root of the issue.
> Fix #255, fallback to default config in ExplicitReturnTypes.

- build.sbt
- project/plugins.sbt
- project/project/plugins.sbt
There were regressions in RC7/RC8 which cause the jar fetcher in
sbt-scalafix to fail. Discovered while testing on scastie.
> Upgrade to coursier RC9.

- scalafix-core/shared/src/main/scala/scalafix/config/ScalafixMetaconfigReaders.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/patch/ReplaceSymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRewriteSuite.scala
- scalafix-tests/input/src/main/scala/test/ReplaceSymbol.scala
- scalafix-tests/output/src/main/scala/fix/package.scala
- scalafix-tests/output/src/main/scala/test/ReplaceSymbol.scala
This is a helpful patch to rename a method. The implementation piggy
backs on the ReplaceSymbol since the two are very similar.
> Add PatchOps.renameSymbol.

- scalafix-core/shared/src/main/scala/scalafix/config/ScalafixMetaconfigReaders.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SemanticCtxImpl.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/RewriteCtx.scala
- scalafix-core/shared/src/main/scala/scalafix/util/SemanticCtx.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRewriteSuite.scala
- .normalized didn't recurse properly
- ctx.addGlobalImports didn't deduplicate symbols
- inserted grouped imports were not sorted alphabetically
- SemanticCtx.names did not include symbols from sugars
- new PatchOps.replaceSymbols which is a wrapper over .replaceSymbol
- SemanticTests constructor overload for backwards compatibility with
scalacenter/scalafix.g8 generated code.
> Various fixes discovered in collection-strawman rewrites.

- build.sbt
- project/Dependencies.scala
- readme/Installation.scalatex
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-core/shared/src/main/scala/scalafix/config/package.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SemanticCtxImpl.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/Sbt1.scala
- scalafix-core/shared/src/main/scala/scalafix/rewrite/ScalafixRewrites.scala
- scalafix-core/shared/src/main/scala/scalafix/util/SemanticCtx.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixRewriteNames.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRewriteSuite.scala
- scalafix-tests/input-sbt/src/main/scala/sbtfix/SbtOneZeroMigrationTest.scala
- scalafix-tests/output-sbt/src/main/scala/sbtfix/SbtOneZeroMigrationTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/SemanticTests.scala
This commit integrates the sbt 1.0 migration rewrites into scalafix. This means that users can use sbt-scalafix for both regular project sources as well as sbt build file sources. To run semantic rewrites on build sources, users will need to install the sbthost compiler plugin globally. Here is what I have setup on my laptop
```scala
// ~/.sbt/0.13/build.sbt
libraryDependencies ++= {
val sbthost = "org.scalameta" % "sbthost-nsc" % "0.3.1" cross CrossVersion.full
val isMetabuild = {
val p = thisProject.value
p.id.endsWith("-build") && p.base.getName == "project"
}
if (isMetabuild) compilerPlugin(sbthost) :: Nil
else Nil
}
```
One neat effect of this change is that it's possible to write custom rewrites for sbt build sources. `> scalafixBuild github:foo/bar/v2` will work just like for `> …
> Integrate sbtfix into scalafix

- project/project/plugins.sbt
- readme/Changelog.scalatex
- readme/Changelog05.scalatex
- readme/Configuration.scalatex
- readme/Faq.scalatex
- readme/Rewrites.scalatex
- readme/src/main/scala/scalafix/Readme.scala
Following feedback from my colleagues to separate the
"new features" section into two parts: end users and rewrite authors.
> Update 0.5.0 changelog.

- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/MetaconfigPendingUpstream.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
Previously, scalafix-cli would fail silently if running a semantic
rewrite with no semanticdb files. Now it fails fast.
Fixes #264
> Fail fast on missing semanticdb.

- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-tests/unit/src/test/scala/scalafix/cli/BaseCliTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/cli/CliTest.scala
Previously, scalafix silently picked the empty rewrite when the input
files were empty and just printed out the message "Running scalafix on 0
files.". Now scalafix reports an error instead with a message saying
which absolute paths it tried to find .scala and .sbt files.
Fixes #295 
cc/ @usrinivasan
> Fail fast when no files are to be fixed.

- build.sbt
testsInputSbt was still causing problems closing the sonatype
repository.
> Clean up noPublish settings.

- readme/Rewrites.scalatex
- scalafix-core/shared/src/main/scala/scalafix/internal/patch/ReplaceSymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rewrite/ExplicitReturnTypes.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rewrite/RewriteCtxImpl.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SemanticTypeSyntax.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/util/TreeOps.scala
- scalafix-tests/input/src/main/scala/test/ExplicitReturnTypes.scala
- scalafix-tests/input/src/main/scala/test/ExplicitReturnTypesShort.scala
- scalafix-tests/output/src/main/scala/test/ExplicitReturnTypes.scala
- scalafix-tests/output/src/main/scala/test/ExplicitReturnTypesShort.scala
Prefixing with `_root_.` is a necessary evil. with `unsafeShortenName`, users have an opt-out solution so I think it's fine to go all-in on safety by default. I think it's most important that the rewrite produces compiling code.
> Harden ExplicitReturnTypes

- project/Dependencies.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rewrite/ExplicitReturnTypes.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/TypeSyntax.scala
- scalafix-tests/input/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypes.scala
- scalafix-tests/input/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesBase.scala
- scalafix-tests/input/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesPathDependent.scala
- scalafix-tests/input/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesShort.scala
- scalafix-tests/input/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesSingleton.scala
- scalafix-tests/output/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypes.scala
- scalafix-tests/output/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesBase.scala
- scalafix-tests/output/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesPathDependent.scala
- scalafix-tests/output/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesShort.scala
- scalafix-tests/output/src/main/scala/test/explicitReturnTypes/ExplicitReturnTypesSingleton.scala
ExplicitReturnTypes can now resolve symbols inside defs and vars.
The only known limitation at the moment is path dependent types are
widened to their non-path-dependent types. A fix for that bug is
pending here https://github.com/scalameta/scalameta/pull/1107
> Upgrade to scalameta v2.0-RC1.

- README.md
I think it's nicer to have this consistent with the website. This is not a Dotty-only tool anymore :)
Also, I don't know why the scaladex thinks `0.3.4+44-1091b539` is the latest version :/
> Align the readme to the website

- project/Dependencies.scala
- readme/Changelog05.scalatex
- readme/Rules.scalatex
- readme/src/main/scala/scalafix/Readme.scala
- scalafix-core/shared/src/main/scala/org/langmeta/internal/ScalafixLangmetaHacks.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/PrintStreamReporter.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoInfer.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala
- scalafix-core/shared/src/main/scala/scalafix/lint/LintCategory.scala
- scalafix-core/shared/src/main/scala/scalafix/lint/LintMessage.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/Rule.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/ScalafixRules.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-tests/input/src/main/resources/rewrites/MyRule.scala
- scalafix-tests/input/src/main/scala/test/NoInfer.scala
- scalafix-tests/input/src/main/scala/test/RemoveXmlLiterals.scala
This is the first scalafix linter rule. There are still a few rough corners around how to display carets around synthetics but the api is already usable. It was a great exercise to implement this linter since I found a few necessary parts missing in testkit to make the experience nice.
> Implement NoInfer linter.

- scalafix-core/shared/src/main/scala/org/langmeta/internal/ScalafixLangmetaHacks.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoInfer.scala
- scalafix-core/shared/src/main/scala/scalafix/lint/LintCategory.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/Rule.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-tests/input/src/main/scala/test/LintAsserts.scala
- scalafix-tests/unit/src/main/scala/scalafix/test/DummyLinter.scala
- Rule names are now attached to their reported patches.
This is necessary to support multiple linters in testkit,
but will also later be necessary for escape hatches.
The implementation is a bit hacky, but that should not leak
into the public api.
- Off-by-one errors in lint asserts
- Lint category id was wrong for composite rules
- Remove trailing `.` when category.id is empty.
- Better detection of linters (but still not perfect).
> Fix linter issues discovered while writing scala-lang blogpost.

- build.sbt
this is better in general... but also, dbuild doesn't understand the
combo-style dependency, so this is needed for Scala community build
compatibility
> depend only on the part of cats actually used

- build.sbt
- scalafix-core/shared/src/main/scala/scalafix/rule/Rule.scala
Assorted fixes in anticipation of a hackathon.
> Assorted fixes

- .travis.yml
- build.sbt
- project/Dependencies.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- bump scalameta dependency
- run mima on 2.11 and 2.12, previously it only ran in 2.12
> Prepare for v0.5.1

- build.sbt
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedTerms.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/ScalafixRules.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixRuleNames.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedTerms.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedTerms.scala
This PR implements the rule described in #238.
In the specific, it removed unused local vals and vars. If litteral expressions are involved, the whole expression is removed, otherwise only the val definition is removed.
I'll try to send another PR for unused def/trait/classes in the near future.
> #238 Rule to remove unused local val and var

- bin/ci-publish.sh
- build.sbt
- project/Dependencies.scala
- project/build.properties
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Closes #374
Not sure what I should change to make this automatically published by the CI
> Cross-build sbt plugin for 0.13 and 1.0

- project/Mima.scala
- project/plugins.sbt
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/DenotationOps.scala
- scalafix-core/shared/src/main/scala/scalafix/syntax/package.scala
- scalafix-tests/shared/src/main/scala/test/DenotationOpsTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/DenotationOpsTest.scala
This seemed like a useful utility so I extracted it from `ExplicitResultTypes`
> Add resultType extension method on Symbol

- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SyntacticRuleSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/SyntacticTests.scala
Return `headOption` instead of `lastOption` in addLeft's implementation.
Additionally, add a unit test, and refactor the syntax tests.
TESTED=unit tests pass
> Fix #373: addLeft's implementation doesn't match its specification

- scalafix-core/shared/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SyntacticRuleSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/ErrorSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/PatchSuite.scala
> Fix #372: addGlobalImport(Importer) is syntactic

- readme/ImplementingRules.scalatex
Clearly broke when crossbuilding was introduced.
> Fix broken links

- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/PrintStreamReporter.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixReporter.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/Rule.scala
- scalafix-tests/unit/src/test/scala/scalafix/cli/CliSyntacticTests.scala
This commit changes the cli to
- use the correct OutputStream for emitting lint messages
- call both fix and check instead of only fix
Review @blorente
> Fix #387, emit linter warnings from cli.

- website/src/main/tut/docs/rules/Disable.md
- website/src/main/tut/docs/rules/DottyVarArgPattern.md
- website/src/main/tut/docs/rules/NoInfer.md
These were leftover from an old experiment with the new website.
> Remove unnecessary tags from docs

- .travis.yml
I just switched to 2.12.3 the entire CI job. I don't see any obvious drawback, since we're running the slow version on scala 2.11.11 anyway.
This fixes the issue with the version of Scaladoc used (reported in #393)
> Publish using 2.12.3 on the CI (this fixes the Scaladoc version issue)

- website/src/main/resources/microsite/data/menu.yml
Link to https://scalacenter.github.io/scalafix/docs/api/scalafix/
instead of the more barren https://scalacenter.github.io/scalafix/docs/api/.
> Tweak API docs link in docs

- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/LazySemanticdbIndex.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ScalafixCompilerDecoder.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/test/scala/scalafix/internal/sbt/ScalafixCompletionsTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ScalafixReflectTests.scala
Previously, all paths were resolves from the base, including absolute
paths. This made it impossible to use `file:/absolute/path`, causing
FileNotFound errors like in
https://gist.github.com/xeno-by/94db732fffc99997ee2c2812ba97e4e2
This commit both fixes that bug and extends the file tab completion to
tab complete from absolute paths `file:/proj<TAB>` to `file:/project` as
well as from `file:../proj<TAB>` to `file:../project`. I'm a bit
surprised the built-inf sbt tab completer doesn't do this by default,
this patch might be worth contributing to sbt.
> File file: tab completion in sbt-scalafix

- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/main/scala/scalafix/internal/cli/ScalafixOptions.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/LazySemanticdbIndex.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/ClassloadRule.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ScalafixToolbox.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixJarFetcher.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ToolClasspathTests.scala
Previously, you needed to include the classpath as part of the scalafix
cli binary in order to use 3rd party dependencies. This commit makes it
possible to use the same scalafix binary with a custom classpath for
loading rules.
Fixes #383
> Add --tool-classpath to cli for file: and class: protocols.

- build.sbt
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/main/scala/scalafix/internal/cli/ScalafixOptions.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/LazySemanticdbIndex.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/ClassloadRule.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ScalafixToolbox.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixJarFetcher.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ToolClasspathTests.scala
build.sbt was becoming unmaintainable, this PR moves non-project related settings to project/ScalafixBuild.scala and replaces allSettings with globalSettings. This should reduce the number of keys to resolve on every sbt reload as well as yield better incremental compilation on reload (sbt builds a compilation unit for each `def/val` in build.sbt). I'm still amazed at the complexity of the scalafix build even after this refactoring, it's almost 500 LOC, but this is at least some improvement (IMO)
> Refactor build.sbt to use project/ScalafixBuild.scala

- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/scala212/src/it/scala/Main.scala
- website/src/main/tut/docs/users/installation.md
This commit makes it possible to enable scalafix for custom configurations like this
```scala
scalafixConfigure(Compile, Test, IntegrationTest)
```
Previously it required more advanced workarounds.
> Fix #331, make is easy to configure custom configurations in sbt-scalafix

- website/src/main/tut/docs/users/installation.md
This missing backquote has dire consequences and break the whole remaining parts of the page.
> Add missing backquote breaking doc

- build.sbt
- project/ScalafixBuild.scala
The CI failed while publishing v0.5.4, I'm not able to reproduce the
compile error in cli/doc so I suspect the problem is related to the
hairy ci-slow command, which triggered commands from the `it:test` task.
This commit removes that part and uses sbt more idiomatically, making
ci-slow stay within the task graph.
> Simplify ci-slow.

- .travis.yml
- project/Dependencies.scala
- project/project/plugins.sbt
After upgrading to 2.12.4 and 2.11.12, we started getting irregular
compile errors in CI, only when the cache is not clean. I don't think
we are doing anything weird with the cache, this commit is to verify if
this regression is caused by misconfiguration in the scalafix builds or
the 2.12.4/2.11.12 upgrade.
> Downgrade to Scala 2.11.11 and 2.12.3.

- scalafix-core/shared/src/main/scala/scalafix/internal/config/ExplicitResultTypesConfig.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-tests/output/src/main/scala/test/explicitResultTypes/ExplicitResultTypesBase.scala
- website/src/main/tut/docs/rules/ExplicitResultTypes.md
> ExplicitResultTypes: skip local implicits 

- build.sbt
- project/ScalafixBuild.scala
For some reason it seems that globalSettings is not respected for
pgpPassphrase, which breaks the publish on tag push from Travis.
This commit moves the settings back to build.sbt and I've manually
confirmed this fixes the issue.
> Fix broken CI publish.

- scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
Scalafmt uses the same dialect with the only difference that we don't
treat `inline` as a keyword here (I think that was a premature choice in
scalafmt)
> Fix #452, use flexible scala dialect.

- scalafix-core/shared/src/main/scala/org/langmeta/internal/ScalafixLangmetaHacks.scala
- scalafix-testkit/src/test/scala/scalafix/testkit/AssertDeltaSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSyntacticTests.scala
This makes it easy to extract the exact position from the cli to
display in the editor.
Fixes #460 
Review @fommil
> Include column number in linter messages

- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/CommentAssertion.scala
@olafurpg look what I found :p
I should always test edge cases.
> Teskit empty assertdiff

- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/main/scala/scalafix/internal/cli/TermDisplay.scala
- s/Downloaded/Completed/, fixes #471
- Use fallback mode by default. The non-fallback mode mixes with the
buffers from reported linter messages.
> Clean up term display output.

- CONTRIBUTING.md
Fixes #459 
Even if we try to automate the process as much as possible by for example letting CI publish artifacts, there are still some parts that are best left for manual checks.
> Document release process.

- .jvmopts
- project/Dependencies.scala
Last time we upgraded to 2.12.4 the CI failed with a missing shapeless
implicit error from case-app. I can reproduce this error locally only on
the first `sbt compile`. Running the command the seconds time succeeds
compilation. I want to see if CI fails again, and investigate if
`-YdisableFlatCpCaching` can fix the error.
EDIT, `-YdisableFlatCpCaching` did not seem to fix the error. Let me try and remove ArgParserImplicits.
> Second stab at 2.12.4.

- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/javaProject/src/main/java/example/Example.java
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
- Fixes #340
- Fixes bug for java-only projects, see part 1 of #489
> Use unmanagedSources instead of unmanagedSourceDirectories.

- scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala
- scalafix-tests/input/src/main/scala/test/Disable.scala
Previously, Disable reported an error on the positions of any
ResolvedName to a disabled symbol, including Input.Synthetic and
Input.Denotation which are invisible and don't appear in the source
file. Now Disable ignores symbol signatures and for synthetics it
points a caret at the position where the synthetic got expanded
and includes the pretty-printed representation of the synthetic
to help make sense of the error message.
Review @vovapolu
> Fix #493, handle synthetics and symbol signatures in Disable.

- project/Mima.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitUnit.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoAutoTupling.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/NoValInForComprehension.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedImports.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedTerms.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveXmlLiterals.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala
- scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/Rule.scala
- scalafix-core/shared/src/main/scala/scalafix/rule/RuleCtx.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-tests/input/src/main/scala/test/ExplicitUnit.scala
- scalafix-tests/input/src/main/scala/test/NoAutoTupling.scala
- scalafix-tests/input/src/main/scala/test/NoValInForComprehension.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedTerms.scala
- scalafix-tests/input/src/main/scala/test/RemoveXmlLiterals.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/EscapeHatchPatches.scala
- scalafix-tests/output/src/main/scala-2.11/test/NoAutoTupling.scala
- scalafix-tests/output/src/main/scala-2.12/test/NoAutoTupling.scala
- scalafix-tests/output/src/main/scala/test/ExplicitUnit.scala
- scalafix-tests/output/src/main/scala/test/NoValInForComprehension.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedTerms.scala
- scalafix-tests/output/src/main/scala/test/RemoveXmlLiterals.scala
- scalafix-tests/output/src/main/scala/test/escapeHatch/EscapeHatchPatches.scala
- website/src/main/tut/docs/rule-authors/glossary.md
This is a really raw first pass.
> Escape hatch on Patch (fix #368)

- project/Mima.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala
- scalafix-core/shared/src/main/scala/scalafix/util/TokenList.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/util/TokenListTest.scala
When working on a scalafix rule for `scala/collection-strawman` I implemented my own logic to get rid of whitespaces. @olafurpg [mentioned in the review](https://github.com/scala/collection-strawman/pull/291/files#r149894285) that it would be nice to have such functionality supported by Scalafix. Later I realized that there was even an issue filed by @gabro to look into that: #370.
I explored a few alternatives to introduce the functionality. There might be better ways to achieve this, so I'd appreciate your feedback and will be willing to accept suggestions.
The code changes in this PR implement the approach that I personally prefer. There are other 2 alternatives available on separate branches (those need some polishing).
1 - `trimLeft` / `trimRight` / `trim` …
> Add methods for dealing with whitespaces

- bin/ci-publish.sh
- build.sbt
- project/ScalafixBuild.scala
To make it easier to try out pre-releases, this commit configures the
CI to publish a -SNAPSHOT to sonatype on every merge.
> Publish SNAPSHOT on merge.

- project/Mima.scala
- scalafix-core/shared/src/main/scala/scalafix/util/TokenList.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/util/TokenListTest.scala
- Addresses #516. The original goal was to do this only for `TokenList.slice` but then I realized that `find` was also inconsistent.
* `find` is not used anywhere in the repo
* `slice` is used in 2 places: `ProcedureSyntax` & `ExplicitResultTypes`. For both of them this change won't cause any harm.
- Fixes a bug in `TokenList.leading` that was causing the first element in the token list (usually `Token.BOF`) being incorrectly dropped.
> Make 'from' parameter in TokenList.slice/find inclusive

- scalafix-core/shared/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedImports2.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedImports.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedImports2.scala
Previously we never removed newlines, which meant that trailing commas
in grouped imports like after `b` in
```scala
import a.{
b,
c
}
```
were left behind, causing a syntax error (in <2.11 only).
> Fix #535, remove trailing comma.

- website/src/main/tut/index.md
It previously linked to a non existent section on the page
> Update link to scalafix.g8

- build.sbt
- project/Dependencies.scala
- project/MultiScalaProject.scala
- project/ScalafixBuild.scala
- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/JGitCompletions.scala
- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/test/scala/scalafix/internal/sbt/ScalafixCompletionsTest.scala
- scalafix-test-utils/src/main/scala/scalafix/internal/tests/utils/Fs.scala
- scalafix-test-utils/src/main/scala/scalafix/internal/tests/utils/Git.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala
This is still pretty raw, but I think it is really important to get a good user experience on sbt. This creates some code duplication between the cli parser generated by caseapp and the sbt parser.
I jumped on that issue because I'm not comfortable using the cli tool like you did in https://github.com/scalacenter/scalafix/pull/511#issuecomment-352814243. I think the most natural way is to run it from the sbt plugin.
The workflow with the cli is not clear in the documentation. I think it would be good to expend this section: https://scalacenter.github.io/scalafix/docs/users/installation#run-scalafix-cli
before running, `scalafix` don't you need to generate the semantic-db?
What is the content of your `scalafix-nightly`? If a user navigates on GitHub and finds this comment …
> Bring scalafix-sbt parser up to par with the cli #518

- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/TypeSyntax.scala
- scalafix-tests/input/src/main/scala/test/explicitResultTypes/ExplicitResultTypesBase.scala
- scalafix-tests/input/src/main/scala/test/explicitResultTypes/ExplicitResultTypesPathDependent.scala
- scalafix-tests/output/src/main/scala/test/explicitResultTypes/ExplicitResultTypesBase.scala
- scalafix-tests/output/src/main/scala/test/explicitResultTypes/ExplicitResultTypesPathDependent.scala
- unary functions were printed as Function0[T] instead of () => T
- local symbols caused MatchError in TypeSyntax.prettify
- upgrade to scalameta 2.1.6 to to enjoy https://github.com/scalameta/scalameta/pull/1216
These fixes combined make ExplicitResultTypes safe to run on over 60k loc in
the akka build. It still has some bugs left, see
https://github.com/scalameta/scalameta/issues/1222
> Fix several ExplicitResultTypes bugs.

- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
@fommil just for you ;-). scalafixCli is more powerful, it's better if you don't revert your fix. However, I'm fixing this task since we don't want to break it!
> Avoid crash in sbt-scalafix's scalafix task when arguments are empty

- .jvmopts
- .travis.yml
- CONTRIBUTING.md
- README.md
- appveyor.yml
- build.sbt
- project/Dependencies.scala
- project/ScalafixBuild.scala
- project/project/plugins.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/project/ScalafixTestUtility.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/project/plugins.sbt
- scalafix-sbt/src/test/scala/scalafix/internal/sbt/ScalafixCompletionsTest.scala
- scalafix-test-utils/src/main/scala/scalafix/internal/tests/utils/SkipWindows.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SyntacticRuleSuite.scala
- scalafix-testkit/src/test/scala/scalafix/testkit/AssertDeltaSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/PatchSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ScalafixReflectTests.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/reflect/ToolClasspathTests.scala
https://github.com/sbt/sbt/issues/3908
> Add AppVeyor as a CI on Window

- project/ScalafixBuild.scala
Prevents the docs from displaying v0.6.0 as the version to install
> Hardcode stable version to 0.5.10 before releasing v0.6-M1.

- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala
- scalafix-tests/input/src/main/scala/test/ProcedureSyntax.scala
- scalafix-tests/output-dotty/src/main/scala/test/ProcedureSyntax.scala
Fixes #557 
The invalid rewrites seem to happen on definition which has a `RightParen` as `defEnd` token, like `def bar(args (Int, Int)) {}`. 
If a `defEnd` is `RightParen`, this rule mistake `closingParen` because [Tokenlist.slice's from param is inclusive](https://github.com/scalacenter/scalafix/pull/534) and `ctx.tokenList.slice(defEnd, bodyStart)` contains two `RightParen`s (`defEnd` and real closing paren).
https://github.com/scalacenter/scalafix/blob/6b7b3656c21e0ee2cae7f22272e63431f77f84bd/scalafix-core/shared/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala#L27-L28
> Fix invalid rewrite for ProcedureSyntax

- scalafix-core/shared/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala
- scalafix-tests/input/src/main/scala/test/ProcedureSyntax.scala
- scalafix-tests/output-dotty/src/main/scala/test/ProcedureSyntax.scala
run ProcedureSyntax on the following:
```scala
def baz[A] { println("baz[A]") }
```
ProcedureSyntax generates uncompilable code.
```scala
def baz: Unit =[A] { println("baz[A]") }
```
```scala
def baz[A]: Unit = { println("baz[A]") }
```
Previously the rule was looking for the right paren. That's not enough if the procedure has  a type parameter.
> Fix ProcedureSyntax rule for type params

- project/Dependencies.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/util/DenotationOps.scala
- scalafix-tests/input/src/main/scala/test/ReplaceSymbol.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/SymbolMatcherTest.scala
The only failing test is due to semanticdb-sbt. To fix it, please merge and release https://github.com/scalameta/semanticdb-sbt/pull/25.
> Upgrade to Scalameta 3.3.1

- build.sbt
- scalafix-cli/src/main/scala/scalafix/cli/Cli.scala
issue: https://github.com/scalacenter/scalafix/issues/260
This PR enable zsh to show rules description on tab completion like this gif.
I couldn't find the way to show description on tab completion (without autocompleting whole element including description) in bash and sbt. 😢
> Add completion for rules description in zsh.

- website/src/main/tut/docs/users/installation.md
sbtfix was an interesting experiment but given that it's incomplete
and no longer being improved it's doing more harm being listed on
the website (see #643) than it's doing good.
> Remove sbtfix and semanticdb-sbt from the installation docs.

- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixEnable.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/customSourceroot/src/main/scala/Main.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/customSourceroot/src/test/scala/MainTest.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
- scalafix-sbt/src/sbt-test/sbt-scalafix/suppress/test
- website/src/main/tut/docs/users/installation.md
Previously, addSbtPlugin(sbt-scalafix) would automatically enable the
semanticdb-scalac compiler plugin and -Yrange scalac options.
This commit removes the automatic installation so that users now need to
manually enable the following settings
```
addCompilerPlugin(scalafixSemanticdb)
scalacOptions += "-Yrangepos"
```
This makes the installation consistent for all users regardless of what
order they define libraryDependencies and scalacOptions.
The installation documentation for sbt-scalafix was pretty complex
before because the automatic setup only worked sometimes.
Fixes #589 
PS. Right after merging this PR we should immediately cut a v0.6.0-M2 release in order to make the installation instructions up-to-date.
> Remove automatic installation of semanticdb-scalac

- website/src/main/tut/docs/rules/Disable.md
I think this is the reason for the mistake in the docs at
https://scalacenter.github.io/scalafix/docs/rules/Disable#examples-1
> typo in docs

- scalafix-core/shared/src/main/scala/scalafix/internal/util/SuppressOps.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/scala212/src/main/scala/IgnoreMe.scala
- website/src/main/tut/docs/users/installation.md
This allows users to exclude/include files that are handled by sbt-scalafix. Fixes #496
> Use unmanagedSources.in(scalafix) in sbt-scalafix

- scalafix-core/shared/src/main/scala/scalafix/internal/rule/RemoveUnusedTerms.scala
- website/src/main/tut/docs/rules/RemoveUnusedTerms.md
> Fix invalid scalacOption.

- bin/ci-publish.sh
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixEnable.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/build.sbt
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/customSourceroot/src/main/scala/Main.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/customSourceroot/src/test/scala/MainTest.scala
- scalafix-sbt/src/sbt-test/sbt-scalafix/cross-build/test
- scalafix-sbt/src/sbt-test/sbt-scalafix/suppress/test
- website/src/main/tut/docs/users/installation.md
Duplicate of #665  that was reverted after merge. Let's not merge this until all changes for v0.6 are ready. I have one more pending PR before it's safe to merge this PR.
Previously, addSbtPlugin(sbt-scalafix) would automatically enable the
semanticdb-scalac compiler plugin and -Yrange scalac options.
This commit removes the automatic installation so that users now need to
manually enable the following settings
```
addCompilerPlugin(scalafixSemanticdb)
scalacOptions += "-Yrangepos"
```
This makes the installation consistent for all users regardless of what
order they define libraryDependencies and scalacOptions.
The installation documentation for sbt-scalafix was pretty complex
before because the automatic setup only worked sometimes.
Fixes #589 
PS. Right after merging this PR we should …
> DO NOT MERGE Remove automatic installation of semanticdb-scalac

- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSyntacticTests.scala
The default console output so far has been geared for debugging implementation
details. This commit moves a lot of noise under --verbose
* Fixes #629
* Fixes #686 
* Fixes #681
> Remove console noise from non-verbose mode.

- scalafix-sbt/src/main/scala/scalafix/internal/sbt/CliWrapperPlugin.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
There were reported heap-space usage problems that are potentially
caused by leaking classloaders in the sbt plugin. I thought that the sbt
task engine cached task results if the depended on settings/tasks don't
change.  This commit is a quick fix to test the hypothesis whether the
sbt plugin is causing problems
> Cache jars and classloaders in sbt-scalafix.

- scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixJarFetcher.scala
Scalafix SNAPSHOT releases use a new version number on every commit so
it's fine to cache SNAPSHOT artifacts forever. This should avoid noisy
output while using pre-releases.
> Set coursier ttl to infinity.

- scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala
- scalafix-cli/src/main/scala/scalafix/internal/cli/ScalafixOptions.scala
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliArgsTest.scala
Sbt automatically parallelizes across projects and configurations so
there is less need to parallelize between individual files. This should help reduce memory pressure, although we will need to do a bigger refactoring to properly fix memory problems.
> Disable parallel processing in sbt by default.

- scalafix-core/shared/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/rule/MissingFinal.scala
- scalafix-tests/input/src/main/scala/test/MissingFinal.scala
- scalafix-tests/input/src/main/scala/test/MissingFinalRewrite.scala
- scalafix-tests/output/src/main/scala/test/MissingFinalRewrite.scala
This PR fixes 3 issues in the `MissingFinal` rule:
**1. Allow ~~individual `TokenPatch` to be suppressed~~ `MissingFinal` rewrites to be suppressed by making individual patches atomic** (#678)
>Side note: My perception is that the `atomic` feature should work the other way around: 
>- patches are atomic by default;
>- if a group of patches need to be atomic, they should be explicitly grouped together;
>
>At the moment, the suppression mechanism only works for rewrites if rule authors remember to call `.atomic` for their patches, which is something very easy to forget. For instance, some other default rules in scalafix (`DottyVarArgPattern`, `DottyVolatileLazyVal`, `LeakingImplicitClassVal`) can't be suppressed because their patches are not made atomic.
>
>UPDATE: actually there is nothing …
> MissingFinal bugfixes

- README.md
- project/ScalafixBuild.scala
Marcelo has made many great contributions to Scalafix via PRs to the Patch
API, extending the suppression mechanism to support annotations and helping
users in the issue tracker. It is my pleasure to recognize his
contributions by welcoming him to the Scalafix team!
> Welcome Marcelo Cenerino to the Scalafix team!

- scalafix-core/shared/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/AnchorOverlapping.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/AnchorWildcard.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/Issue694.scala
Fixes:
- #693: `scalafix:ok` (wildcard) incorrectly re-enables all rules after the end of its corresponding expression. This includes rules that were already suppressed before the expression (example [here](https://github.com/scalacenter/scalafix/issues/693#issuecomment-381344041)). With this fix, `scalafix:ok` now only re-enables rules suppressed by itself
- #694: a `scalafix:ok` comment is currently interpreted as two independent `off` and `on` instructions whose end offset is EOF. This causes unpredictable results when +2  expressions marked with `scalafix:ok` overlap (see example [here](https://github.com/scalacenter/scalafix/issues/694#issuecomment-384107792)). With this fix, `scalafix:ok` comments are now treated as a single `off` instruction whose end offset is the last position of …
> Bug fix: 'scalafix:ok' must not re-enable rules already suppressed

- website/src/main/tut/docs/users/installation.md
Changes:
- added how-to instruction on using semanticdb plugin via maven profile instead of manual download
- added version compatibility table to installation doc
Testing:
- run `sbt website/makeMicrosite`
- run `jekyll serve` in `website/target/site` and verified the updated text is correct
Questions:
I wasn't sure if should `site.scalametaVersion` property so I hardcoded the correct version of the plugin instead. Feel free to reach out to me if you want it done differently.
> Fix and extend maven installation docs

- scalafix-core/shared/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/AnchorOverlapping.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/AnchorUnused.scala
- scalafix-tests/input/src/main/scala/test/escapeHatch/AnnotationUnused.scala
- fix missing cases where `scalafix:on` is not reported as unused:
- sequence of multiple `scalafix:on`
- after a rule is turned OFF and then ON again
- report unused rule when it is wrapped by triple quotes in `@SuppressWarnings`
- minor refactorings in `EscapeHatch` to save some lines of code
Each change is in a separate commit.
> Fix: EscapeHatch is not reporting unused 'scalafix:on' in some cases

- scalafix-core/shared/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
- scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxBase.scala
Addresses https://github.com/scalacenter/scalafix/issues/660
This PR improves the report messages of `DisableSyntax.{noSemicolons, noTabs, noXml}` from  messages like `noSemicolons is disabled` to those like `semicolons are disabled`.
> Improve DisableSyntax's error message

- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/rule/RuleSuite.scala
This constructor uses the BuildInfo types directly simplifying the code
that scalafix.g8 needs to generate.
> Expose simple constructor for SemanticRuleSuite

- build.sbt
- scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixTestkitPlugin.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitProperties.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/rule/RuleSuite.scala
With v0.6 testkit will need the full classpath of the input project.
Previously, testkit only needed the input classDirectory.
This commit introduces a new ScalafixTestkitPlugin to help abstract
over how arguments are passed from the build to testkit.
This simplifies the g8 template and also makes it easier to later
customize what data is passed from the build without modifying g8
templates.
Manually tested on typelevel/cats migration rewrites and seems to work well.
> Add ScalafixTestkitPlugin to simplify g8 template.

- CONTRIBUTING.md
- project/ScalafixBuild.scala
- release step failed by trying to publish the sbt plugin
- CONTRIBUTING.md still references the sbt plugin project
> Remove leftovers from sbt plugin

- bin/ci-publish.sh
By using sonatypeReleaseAll we risk releasing artifacts for bloop
in case a parallel release happens. This commit changes the release
script to use sonatypeRelease that fails fast in case there are more
than one staging repository, meaning we'll have to manually release in
case of conflict.
cc/ @jvican
> Fail fast in case of sonatype release conflicts [ci skip]

- build.sbt
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/ValidatedArgs.scala
- scalafix-core/shared/src/main/scala/scalafix/internal/v1/package.scala
- scalafix-core/shared/src/main/scala/scalafix/v1/SemanticDoc.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitPath.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitProperties.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
This is not ready for merge, it is meant only to demonstrate a small set of changes that would fix scalafix-testkit support for build tools using a sourceroot format like Pants/Bazel/Buck.  This PR currently breaks SBT usage.
> Support sourceroot in testkit

- project/Dependencies.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/PrettyTypeSuite.scala
Updated PrettyTypeFuzzSuite to ignore expected failures.
The fuzz test needs improvement to reduce false negatives.
> Upgrade to scalameta v4.0.0-M6.

- build.sbt
The recent SNAPSHOT relases published modules ch.epfl.scala:cli instead
of ch.epfl.scala:scalafix-cli
> Set moduleName setting

- scalafix-reflect/src/main/scala/scalafix/internal/reflect/RuleDecoderOps.scala
- scalafix-reflect/src/main/scala/scalafix/v1/RuleDecoder.scala
- scalafix-tests/input/src/main/scala/test/ServiceLoaders.scala
- scalafix-tests/output/src/main/scala/test/ServiceLoaders.scala
- scalafix-tests/unit/src/main/resources/META-INF/services/scalafix.v1.Rule
Previously, custom rules had to be configured through the 'class:FQN'
option but this was error prone since it's easy to mess up the rule
FQN and it's long to type. This commit adds support for loading custom
rules from the classpath using JDK ServiceLoaders:
https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html
```
// Before
rules = [ "class:com.bar.FooRule" ]
// After
rules = [ FooRule ]
```
> Support loading custom rules by their name instead of FQN

- project/Dependencies.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/DocSemanticdbIndex.scala
- scalafix-core/src/main/scala/scalafix/internal/util/PrettyType.scala
- scalafix-core/src/main/scala/scalafix/internal/v0/LegacyCodePrinter.scala
- scalafix-core/src/main/scala/scalafix/v1/Sym.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
- scalafix-tests/input/src/main/scala/test/DisableSimple.scala
This is most likely the last milestone release.  There were two major
breaking changes that are addressed in this commit.
- new synthetics are now an ADT so we implement a code printer to
produce the old synthetics
- accessibility is now an ADT
> Upgrade to scalameta v4.0-M8

- scalafix-core/src/main/scala/scalafix/internal/util/Inspect.scala
- scalafix-core/src/main/scala/scalafix/util/Api.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/util/InspectSuite.scala
Based on feedback from @MasseGuillaume and @ShaneDelmore, there's been missing a utility to inspect the structure of trees. `Tree.structure` is too dense to be helpful. This commit inlines the sources from the repo https://github.com/masseguillaume/scalameta-structure. Thank you @MasseGuillaume for implementing scalameta-structure! I did my best to preserve the git history, but I suspect I messed it up somehow 😅
> Inline scalameta-structure into repo

- scalafix-core/src/main/scala/scalafix/internal/v1/FromProtobuf.scala
- scalafix-core/src/main/scala/scalafix/v1/Annotation.scala
- scalafix-core/src/main/scala/scalafix/v1/SType.scala
- scalafix-core/src/main/scala/scalafix/v1/Signature.scala
It can't be called `Type` becuase that would conflict with
`scala.meta.Type`. However, `Tpe` is difficult to pronounce/read.
Instead, `SType` is easier to read and understand and the "S" can be
interpreted as "Scalafix" or "SemanticDB".
> Rename Tpe to SType.

- scalafix-core/src/main/scala/scalafix/internal/util/PositionSyntax.scala
- scalafix-core/src/main/scala/scalafix/internal/v0/LegacySyntacticRule.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/DocFromProtobuf.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/InternalSemanticDoc.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/PositionSearch.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/SymtabFromProtobuf.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/package.scala
- scalafix-core/src/main/scala/scalafix/v1/STree.scala
- scalafix-core/src/main/scala/scalafix/v1/SType.scala
- scalafix-core/src/main/scala/scalafix/v1/SemanticDoc.scala
- scalafix-core/src/main/scala/scalafix/v1/SymbolInfo.scala
- scalafix-core/src/main/scala/scalafix/v1/package.scala
- scalafix-reflect/src/main/scala/scalafix/internal/v0/LegacyInMemorySemanticdbIndex.scala
- scalafix-tests/input/src/main/scala/test/ExplicitSynthetic.scala
- scalafix-tests/output/src/main/scala-2.11/test/ExplicitSynthetic.scala
- scalafix-tests/output/src/main/scala-2.12/test/ExplicitSynthetic.scala
- scalafix-tests/unit/src/main/resources/META-INF/services/scalafix.v1.Rule
- scalafix-tests/unit/src/main/scala/scalafix/test/ExplicitSynthetic.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/BaseSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/util/InspectSuite.scala
This commit exposes the new SemanticDB Synthetics in the public Scalafix
API. For reference, there is an example ExplicitSynthetic rule
that inserts explicit `.apply` and inferred type parameters for infix
operators. This kind of refactoring would have been significantly more
difficult with the v0 API.
Other fixes:
- Ignore non-existing files instead of throwing NoSuchFileException:
This comes up when reading stale semanticdb files of removed files.
- s/NoTpe/NoType/
- render `.inspect` with width 80 instead of 1.
- make `diagnostics` an iterator instead of eager list
> Expose synthetics in v1 API

- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/CompletionsOps.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-tests/input/src/main/scala-2.12/test/RemoveUnusedImportsTrailingCommas.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedImportsCommas.scala
- scalafix-tests/output/src/main/scala-2.12/test/RemoveUnusedImportsTrailingCommas.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedImports2.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedImportsCommas.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
This was awfully painful since the code is tricky to follow. It would
probably be significantly simpler if we simply removed all import tokens
and synthesized tokens for remaining comments. Either way, the primary
improvement from this commit is that we have a slightly simpler rule for
deciding how to remove commas
- always remove leading comma (for importers + importees)
- remove trailing comma for the last unused importer/importee before
the first used importer/importee.
Fixes #653
> Polish handling of trailing commas for removed imports

- scalafix-core/src/main/scala/scalafix/internal/config/MetaconfigOps.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/Rules.scala
- scalafix-core/src/main/scala/scalafix/v0/Rule.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/RuleInstrumentation.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ScalafixToolbox.scala
- scalafix-reflect/src/main/scala/scalafix/v1/RuleDecoder.scala
Those methods can't easily be upstreamed since some of them are
scalameta/scalafix specific.
> Rename MetaconfigPendingUpstream to MetaconfigOps (fix #499)

- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedImportsRename.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedImportsRename.scala
Unused renames may still have significant meaning so removing them may
cause compile errors.
Fixes #614
> Unimport unused renames instead of removing them

- scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
- scalafix-core/src/main/scala/scalafix/lint/RuleDiagnostic.scala
- scalafix-tests/unit/src/main/scala/scalafix/internal/tests/utils/Fs.scala
- scalafix-tests/unit/src/main/scala/scalafix/internal/tests/utils/Git.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffSuite.scala
Example output:
commit message: r0
```scala
object Code {
val a = 42
}
```
commit message: r1
```scala
object Code {
var a = 42
}
```
```
/tmp/scalafix1367068904944601960/code.scala:2:3: error: [DisableSyntax.keywords.var] 
2018-08-31 12:01 Guillaume Massé e27e0825 - r1
var is disabled
var a = 42
^^^
```
> Add --blame to show offending commit of Diagnostic (fix #485)

- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitProperties.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
This makes it possible for users to place SemanticDB files in a
different directory than classDirectory and still use Scalafix.
It turns out some cli tests were passing by accident because the
classloader we used to load SemanticDB already included the missing
SemanticDB files thanks to the parent classloader. After this commit,
the classloader has no parent so that the test fixture doesn't
accidentally pick up resources from the parent classloader.
Fixes #879
> Respect -P:semanticdb:targetroot

- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedStatements.scala
- scalafix-tests/output/src/main/scala/test/RemoveUnusedStatements.scala
Fixes #626 
This is a workaround that tries to match by pos.start instead of full position.
I'm sure there are edge cases I haven't thought of, wdyt @olafurpg?
/cc @joan38
> Remove unused on top-level template statements

- docs/rules/DisableSyntax.md
- scalafix-core/src/main/scala/scalafix/config/CustomMessage.scala
- scalafix-core/src/main/scala/scalafix/config/Regex.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntaxConfig.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
- scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxBase.scala
I think the best way to see what I've changed is to look at the [updated docs](https://github.com/scalacenter/scalafix/blob/64e39aaa13120504dfb4ea927901ef5f4c528358/docs/rules/DisableSyntax.md).  To summarize:
1. Now error messages will underline the whole area of matched regex
2. The relevant capture group can be specified, in case you have complicated regex's which may match on parts which aren't helpful in the error message
3. scalafix errors which came from a regex match have access to the capture groups for substitution in the error messages.
I'm not dead set on any of the naming or formatting I've chosen.  Feel free to have me change them
> Improve regex integration with DisableSyntax 

- .travis.yml
- project/Dependencies.scala
- project/project/plugins.sbt
- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
- scalafix-reflect/src/main/scala/scalafix/internal/v0/LegacyInMemorySemanticdbIndex.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/BaseSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/Classpaths.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/PrettyTypeSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/v1/SymbolInformationSuite.scala
This release has faster tree traversal, supports more Scala versions,
works on Java 11 and is ~8mb smaller than v4.0.0.
> Upgrade to Scalameta v4.1.0

- scalafix-cli/src/main/scala/scalafix/internal/v1/FileException.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/Rules.scala
- scalafix-tests/unit/src/main/resources/META-INF/services/scalafix.v1.Rule
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSyntacticSuite.scala
Previously, the stack trace from unexpected errors didn't include
the file path being processed. Now the error includes what file is
being processed and the stack trace is truncated to only include
relevant parts.
Supersedes #908
> Include filename for unexpected errors.

- project/build.properties
Here are release notes and there is no significant breakage.
https://developer.lightbend.com/blog/2018-07-02-sbt-1-2-0/index.html
https://developer.lightbend.com/blog/2018-08-07-sbt-1-2-1/index.html
https://developer.lightbend.com/blog/2018-09-14-sbt-1-2-3/index.html
https://developer.lightbend.com/blog/2018-10-08-sbt-1-2-4-and-nightly-builds/index.html
https://developer.lightbend.com/blog/2018-10-17-sbt-1-2-6/index.html
https://developer.lightbend.com/blog/2018-11-30-sbt-1-2-7-and-sbt-0-13-18/index.html
sbt 1.2 has many zinc optimizations :)
---
As a release note for 1.2.4 said, it is necessary to run `clean` after updated sbt
> Please run clean after updating since sbt 1.2.4 includes a fix in the incremental compiler.
> Upgrade sbt to 1.2.7

- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntaxConfig.scala
- scalafix-tests/input/src/main/scala/test/DisableSyntaxMoreRules.scala
Currently, the rule for disabling universal equality still allows for universal inequality.  This PR addresses that.
> Add universal inequality cases and tests

- docs/developers/tutorial.md
Instruct to use `--rules=` rather than `--rules` so it also works with the sbt input key (#948).
> Give better guidance on custom rule running

- .travis.yml
Travis failed to install `oraclejdk8` in recent PR https://travis-ci.org/scalacenter/scalafix/jobs/567473636#L167
`openjdk8` is chosen, since `openjdk11` fails to download `sbt-unidoc` on `TEST="2.11"` job
https://travis-ci.org/scalacenter/scalafix/jobs/567475070#L2403
> Fix travis failing jdk installation

- docs/rules/external-rules.md
- website/i18n/en.json
Follow-up #974 
Sorry, I have forgoten to confirm sidebar in the previous PR.
> Fix "Using external rules" not shown in sidebar

- project/Dependencies.scala
- scalafix-core/src/main/scala/scalafix/internal/v1/package.scala
- scalafix-core/src/main/scala/scalafix/v1/SemanticDocument.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitPath.scala
- scalafix-tests/input/src/main/scala/test/Filename With Spaces.scala
- scalafix-tests/output/src/main/scala/test/Filename With Spaces.scala
Upgrades to scalameta 4.2.1 to ensure proper semanticdb files are generated for such files.
Fixes #972.
> Fix issues handling source files with spaces in their path.

- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
- scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxNoValPatterns.scala
Fixes #992. Next cases should be allowed:
1. total wildcard: `val _ = "Something"`;
2. tuple element wildcard: `val (first, _) = ("Foo", "Bar")`.
Wildcards in non-total cases such as case classes or sequences still won't be allowed.
> #992 allow 'DisableSyntax.noValPattern' for wildcard patterns

- scalafix-core/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/PatchSuite.scala
Right now if you use `addGlobalImport` on a file that doesn't have any imports, it will just drop in the new imports one token ahead of the first statement in the file, which is inconvenient if that statement is preceded by a comment:
```scala
package foo.bar
/**
* API docs for A here
*/
import whatever
object A
```
This change just checks whether the token one token ahead of the first statement is a comment, and if it is, it moves to the left of that. This could still go wrong, and it wouldn't be too hard to make the logic for picking this position much more robust (I'd be happy to take a stab at that if there's interest).
> Adjust position for first imports to precede comment

- docs/users/installation.md
Following up conversation with @SethTisue on #1046, I'm updating the docs to include reference to the Gradle plugin for Scalafix that myself and @fsanjuan have been developing: https://github.com/cosmicsilence/gradle-scalafix . The current status of the project is described [here](https://github.com/cosmicsilence/gradle-scalafix#project-status)
> Update docs to include reference to Gradle plugin

- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
Current behaviour:
```
java.lang.IllegalArgumentException: Missing /* */ comment at the top of Input.VirtualFile("scalafix-rules/src/main/scala/fix/Foo.scala", "package fix
```
Would be nicer to just use [`Input.VirtualFile.path`](https://github.com/scalameta/trees/blob/master/scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Input.scala#L74) in the message.
> Fix string representation of `Input.VirtualFile` in exception message

- scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-tests/input/src/main/scala-2.12/test/explicitResultTypes/ExplicitResultTypesShort.scala
- scalafix-tests/output/src/main/scala-2.12/test/explicitResultTypes/ExplicitResultTypesShort.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
Fixes #990
Thank you all for your hard work to make our migrations / linting easier!
This includes the following value conversion in ExplicitResultType rule:
- from Option.empty[T] to None
- from List.empty[T] to Nil
- from Seq.empty[T] to Nil
While I haven't come up with any problem if Seq.empty[T] value is converted to Nil as long as its type is annotated as Seq[T], please let me know if there is any.
> convert empty values to None or Nil in ExplicitResultType rule

- .gitignore
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
> scalafix_cli - jdk11

- project/Dependencies.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SyntacticRuleSuite.scala
This reverts commit 78c9d049e2ccd2536519c764135a59e80eebb604.
ScalaTest v3.1 has several breaking changes that makes the latest Scalafix integration fail in Pants. I'm reverting this upgrade for now since the ScalaTest upgrade was done without much thought (it wasn't even mentioned in the release notes). We'll need to find another long-term solution to deal with this situation, either require clients to upgrade to ScalaTest 3.1 (which is a tall order for large codebases) or use another testing framework in Scalafix testkit.
> Revert "Update scalatest to 3.1.0"

- scalafix-core/src/main/scala/scalafix/internal/config/ParserConfig.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SyntacticRuleSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/DialectSuite.scala
Previously, Scalafix failed to parse sources that used literal types,
which got introduced in 2.13.  Now, Scalafix uses the correct parser
dialect so that literal types are understood correctly. Fixes #1045
> Support literal types

- scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/ExplicitResultTypesConfigSuite.scala
We have had several reported issues about Scalafix not working due to
the 2.12.11 requirement of the ExplicitResultTypes rule. This commit
updates the error message to explain the problem and include
instructions on how to fix this problem.
> Clarify ExplicitResultTypesConfigSuite config error message

- docs/users/installation.md
- website/i18n/en.json
- website/package.json
This pr just adds in a small note to remind users that may be new to scalafix that the `-Ywarn-unused` options differs a bit between scala versions (although that info is in the `RemoveUnused` section.
I also updated docusaurus to the latest, built it locally and ensured that things still look good.
closes #1089
> Small update to intro docs

- docs/users/installation.md
Although I might miss 0.9.14 release, please let me send a PullRequest to include this change to be included in an installation guide column.
https://github.com/scalacenter/sbt-scalafix/pull/89
It would be nicer to be documented,  although I would think we needn't to hurry it.
> include semanticEnabled settings in installation

- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
Should fix https://github.com/scalacenter/scalafix/issues/1110, as failure to look up the target root triggers the presentation compiler, with a version that might not match the bytecode injected (see https://github.com/scalacenter/scalafix/issues/998).
The `SemanticDBPlugin` from sbt 1.3.x duplicates the `targetroot` option on `Test` (or any configuration that extends one where scalafix is enabled) via parent configuration delegation.: https://github.com/sbt/sbt/blob/a1b54d027a87654cbc782270872afc1b4c5a8852/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L42-L45.
In that case, `semanticdb-scalac` picks the last: https://github.com/scalameta/scalameta/blob/de206a796c7558f0ceb8bf3a557f3296f0ac34de/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOp …
> align behavior with semanticdb-scalac: last arg wins

- README.md
- project/ScalafixBuild.scala
Brice has made a lot of fantastic contributions lately improving the
experience of using scalafix for both end users and rule authors.
I'm really happy to welcome him as a scalafix maintainer!
> Welcome Brice Jaglin to the team!

- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixImpl.scala
- scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java
Follow-up of https://github.com/scalacenter/scalafix/pull/1118
> expose scalafix 2.13 patch version in scalafix-interfaces

- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
This PullRequests suppress RemoveUnused configuration error if scalac options contain `-Xlint` or `-Xlint:unused`, both of which generate and add unused diagnostics message string into SemanticDB.
Note: There might be discussions at the following point.
Currently this PullRequest supports no explicit linting option (just `-Xlint`) or only a linting option per a line (`-Xlint:unused`) for implementation simplicity. IMHO this covers majority of `-Xlint` usage, as long as I check with "-Xlint" GitHub search.
This PR does NOT support multiple linting options together like `-Xlint:unused,constant`, wildcard like `-Xlint:_`, nor unary operator like `-Xlint:-constant,_`.
If we want to support multiple linting options notation or else above, it may need to introduce a simple scalac option parser …
> respect -Xlint or -Xlint:unused scalac options in RemoveUnused rule

- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-tests/input/src/main/scala/test/RemoveUnusedImports.scala
I think `importees` can be remove if `forall(_.is[Importee.Unimport])`
> improve RemoveUnused rule

- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
* I naively assumed a `URLClassLoader` would require URL(s), and it did work for a while (the `file:` prefix is supported in `java.nio.file.Paths.get()`), until my path contained '%' which was not supposed to be escaped
* Seeing that repeating the argument did not work, I had to look up the source code to figure out the usage of a single, `java.ioFile.pathSeparator`-separated argument value
> clarify syntax of --tool-classpath

- scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java
- scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixArguments.java
https://github.com/joan38/mill-scalafix/pull/3#discussion_r440642136
As mentioned there, I think it's still interesting to keep these overloads for power-users.
> scalafix-interfaces: advise against using classloader overloads

- .github/workflows/ci.yml
- build.sbt
- project/Mima.scala
- project/ScalafixBuild.scala
Useful for https://github.com/scalacenter/scalafix/pull/1176 and to prepare for 1.0
* scalafix-cli
* scalafix-core
* scalafix-interfaces
* scalafix-reflect
* scalafix-rules
* scalafix-testkit
> re-enable MiMa against latest stable version for published modules

- scalafix-rules/src/main/scala/scalafix/internal/rule/CompilerTypePrinter.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-tests/input/src/main/scala/test/explicitResultTypes/LocalImplicits.scala
- scalafix-tests/input/src/main/scala/test/explicitResultTypes/SkipLocalImplicits.scala
- scalafix-tests/output/src/main/scala/test/explicitResultTypes/LocalImplicits.scala
- scalafix-tests/output/src/main/scala/test/explicitResultTypes/SkipLocalImplicits.scala
- scalafix-tests/output/src/main/scala/tests/ExplicitResultTypesRefinement.scala
- scalafix-tests/output/src/main/scala/tests/RscCompat.scala
Fix #1180 
Also fix: `ExplicitResultTypes.skipLocalImplicits = false` has no effect.
> Fix #1180 - ExplicitResultTypes for implicit members of local traits

- docs/developers/before-you-begin.md
- docs/developers/local-rules.md
- docs/developers/setup.md
- docs/developers/tutorial.md
- website/i18n/en.json
- website/sidebars.json
Merge only when https://github.com/scalacenter/sbt-scalafix/pull/121 is released
This is the public documentation for https://github.com/scalacenter/sbt-scalafix/pull/100. It's a bit late as I found https://github.com/scalacenter/sbt-scalafix/pull/121 to be key for any non-2.12 project to use it. Since the original PR was not thoroughly reviewed/advertized, I guess it would be nice to iterate on the implementation itself (that we have been using internally with `ScalafixTestkitPlugin` on a multi-project build), as documentation highlights possible improvements & shortcomings.
I decided to create a separate section as a first step, since integrating it in the current tutorial was quite demanding. Depending on the main target for Scalafix rules development (lib or application authors?), …
> Document local rules for sbt builds

- docs/users/installation.md
Merge only when https://github.com/scalacenter/sbt-scalafix/pull/126 is released
> document scalafixAll InputKey

- docs/developers/tutorial.md
Merge only when https://github.com/scalacenter/sbt-scalafix/pull/123 is released.
The `coursier-interface` facade is pretty poor when it comes to resolver helpers.
> sbt scalafixResolvers: coursiersmall -> coursierapi

- docs/rules/ExplicitResultTypes.md
- docs/users/installation.md
Merge only when https://github.com/scalacenter/sbt-scalafix/pull/121 is released
Improves https://github.com/scalacenter/scalafix/issues/998
> document sbt-scalafix scalafixScalaBinaryVersion

- project/ScalafixBuild.scala
```
2020-07-04T00:13:45.0599582Z [warn] 	module not found: ch.epfl.scala#scalafix-reflect_2.13.2;0.9.18
2020-07-04T00:13:45.0600207Z [warn] ==== local: tried
2020-07-04T00:13:45.0600786Z [warn]   /home/runner/.ivy2/local/ch.epfl.scala/scalafix-reflect_2.13.2/0.9.18/ivys/ivy.xml
2020-07-04T00:13:45.0601153Z [warn] ==== public: tried
2020-07-04T00:13:45.0601779Z [warn]   https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-reflect_2.13.2/0.9.18/scalafix-reflect_2.13.2-0.9.18.pom
2020-07-04T00:13:45.0602312Z [warn] ==== local-preloaded-ivy: tried
2020-07-04T00:13:45.0602855Z [warn]   /home/runner/.sbt/preloaded/ch.epfl.scala/scalafix-reflect_2.13.2/0.9.18/ivys/ivy.xml
2020-07-04T00:13:45.0603330Z [warn] ==== local-preloaded: tried
2020-07-04T00:13:45.0603920Z [warn] …
```
> fix MiMA after 0.9.18 release with a new Scala patch version

- bin/test-release.sh
- project/Dependencies.scala
https://github.com/scala/scala/releases/tag/v2.12.12
https://github.com/scalameta/scalameta/releases/tag/v4.3.20
https://github.com/scalameta/scalameta/releases/tag/v4.3.19
> support for Scala 2.12.12

- scalafix-tests/input/src/main/scala/test/AnchorPatches.scala
- scalafix-tests/output/src/main/scala/test/AnchorPatches.scala
Trying to re-enable this test for all scala versions. Right now it fails for 2.13. This test uses RemoveUnused Rule and specifically here will remove imports. This test requires `-Wunused:imports` in 2.13.
After debugging in 2.13, I can see that `scalacOptions` that is set in `TestkitProperties.scala` file is equal to `List(-target:jvm-1.8, -Wunused:imports, -encoding, UTF-8, -feature, -unchecked)`. So it's supposed to work, but it's not. In fact, there are no diagnostic in SemanticDocument of this file, so the rule is not able to remove unused imports. 
* Weirdly removing `scalacOptions += "-Ywarn-unused" ` from `build.sbt` makes the test run, but many other tests will fail like RemoveUnusedStatements (still in 2.13)
I am not able to understand why changing `build.sbt` makes the test …
> Fix AnchorPatches test

- docs/developers/tutorial.md
I followed the Contributing docs for [Documentation](https://github.com/scalacenter/scalafix/blob/master/CONTRIBUTING.md#documentation), and the documentation website looks as expected on my local.
I believe following this documentation update solves both of these issues: [1077](https://github.com/scalacenter/scalafix/issues/1077) and [1074](https://github.com/scalacenter/scalafix/issues/1074).
Documentation around `[defaultPattern]` usage can also be found in Ammonite [docs](https://ammonite.io/) and [tests](https://github.com/lihaoyi/Ammonite/blob/master/amm/repl/src/test/scala/ammonite/session/ProjectTests.scala#L69-L79).
I have verified using `[defaultPatten]` works for resolving custom ScalaFix rules I've published to an internal / private company artifactory registry.
> Update tutorial's ivy resolver docs.

- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/ScalafixImplSuite.scala
Right now, even if you specify a config file = None, scalafix still reads the default config path. 
The goal is to document this behavior through a test
> Fix ScalafixImplSuite test and add a test for configuration path

- build.sbt
- docs/developers/semantic-tree.md
- docs/developers/semantic-type.md
- docs/developers/symbol-information.md
- docs/developers/symbol-matcher.md
- docs/developers/tutorial.md
- scalafix-docs/src/main/scala/docs/website.scala
- scalafix-docs/src/main/scala/scalafix/docs/PatchDocs.scala
- scalafix-tests/unit/src/main/scala/scalafix/test/ExplicitSynthetic.scala
* use the new api for SemanticTree
* add @unchecked for non exhaustive pattern matching (in doc)
fixes #1190
> Fix warn messages in doc

- scalafix-testkit/src/main/scala/scalafix/internal/testkit/AssertDelta.scala
- scalafix-testkit/src/main/scala/scalafix/internal/testkit/CommentAssertion.scala
- scalafix-tests/input/src/main/scala/test/DisableSyntaxMoreRules.scala
- scalafix-tests/input/src/main/scala/test/NoFinalize.scala
- scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxBase.scala
- scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxNoValPatterns.scala
This pull request ensures that the testkit checks the whole caret (`^^^^`) position range. Before only the range start was tested.
> check the whole caret position in the testkit

- scalafix-rules/src/main/scala/scala/meta/internal/pc/ScalafixGlobal.scala
- scalafix-tests/input/src/main/scala/test/explicitResultTypes/ExplicitResultTypesPathDependent.scala
- scalafix-tests/input/src/main/scala/tests/ExplicitResultTypesImports.scala
- scalafix-tests/output/src/main/scala/test/explicitResultTypes/ExplicitResultTypesPathDependent.scala
- scalafix-tests/output/src/main/scala/tests/ExplicitResultTypesImports.scala
Best reviewed by commits (as each of them should be green test-wise): the first one prevents compilation error when running the rule against a codebase using https://github.com/tpolecat/doobie (see commit message and comments in test), while the second improve reference shortening for path-dependent types.
> ExplicitResultTypes path-dependent types import bugfix & tweaks

- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/ArgsSuite.scala
this will future-proof you against scala/scala#9292, which will
be included in Scala 2.13.4.
ArrayCharSequence only existed to plug a whole in the Java standard
library which, as of Java 8, is now plugged. we are likely to
deprecate ArrayCharSequence, so this is actually code improvement
and not an ugly workaround
> adapt to scala/scala#9292 (ArrayCharSequence)

- .jvmopts
I don't know anything about this flag, but JDK 15 doesn't accept it.
A possible alternate approach here would be to add `-XX:+IgnoreUnrecognizedVMOptions`.
> allow building on JDK 15

- .github/workflows/ci.yml
Warn from setup-scala: The `set-env` command is deprecated and will be disabled on November 16th
> Update setup-scala githubAction

- scalafix-core/src/main/scala/scalafix/internal/patch/ReplaceSymbolOps.scala
- scalafix-tests/input/src/main/scala/org/scalatest_autofix/Matchers.scala
- scalafix-tests/input/src/main/scala/tests/scalatest_autofix/ScalatestAutofixRule.scala
- scalafix-tests/input/src/main/scala/tests/scalatest_autofix/ScalatestAutofixRule2.scala
- scalafix-tests/output/src/main/scala/org/scalatest_autofix/matchers/should/Matchers.scala
- scalafix-tests/output/src/main/scala/tests/scalatest_autofix/ScalatestAutofixRule.scala
- scalafix-tests/output/src/main/scala/tests/scalatest_autofix/ScalatestAutofixRule2.scala
- scalafix-tests/unit/src/main/resources/META-INF/services/scalafix.v1.Rule
- scalafix-tests/unit/src/main/scala/scalafix/test/ScalatestAutofixRule.scala
Previously, the ScalaTest autofix rule didn't properly handle cases with
renamed imports due to a bug in Scalafix. This commit fixes that bug so
that the ScalaTest rule works correctly as expected.
> Fix Patch.replaceSymbols bug that affects ScalaTest rule.

- docs/users/installation.md
Hi, thanks for your linter :) 
I integrated it in Mega-Linter, can I put a link here ? :)
Internal documentation is https://nvuillam.github.io/mega-linter/descriptors/scala_scalafix/, do you have remarks ?
Best regards :)
> Add Mega-Linter in list of integrating tools

- docs/rules/RemoveUnused.md
- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnusedConfig.scala
Follows https://github.com/scalacenter/scalafix/pull/1318
> RemoveUnused: add example for patternvars & add reference to scala 2.13

- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
Follows https://github.com/scalacenter/scalafix/pull/1215
Confirms that https://github.com/scalameta/scalameta/pull/2216 is fixed
> ensure scalacOptions are honored in 2.13

- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
The state before the fix. It possible to reproduce by running multiple time the test on-demand with scalacOptions
The presentation compiler is never closed.
> Close global after compute ondemand semanticdb files

- docs/users/installation.md
`sbt-scalafix` is versioned independently (at least for SNAPSHOTs) and we don't have its latest SNAPSHOT version here, so it's `scalafix-interfaces` the user should override to get the latest `scalafix-core` & `scalafix-rules`.
> fix instructions to use nightlies

- scalafix-rules/src/main/scala/scalafix/internal/rule/ProcedureSyntax.scala
- scalafix-tests/input/src/main/scala/test/ConstructorProcedureSyntax.scala
- scalafix-tests/output/src/main/scala/test/ConstructorProcedureSyntax.scala
* code inspired from [ConstructorProcedureSyntax](https://github.com/ohze/scala-rewrites/blob/dotty/rewrites/src/main/scala/fix/scala213/ConstructorProcedureSyntax.scala)
* We don't remove braces in case of 1 statement
fixes #1235
> Handle secondary constructor in Procedure syntax

- build.sbt
- project/ScalafixBuild.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-tests/input/src/main/scala-2.13/test/RemoveUnusedPatternVars.scala
- scalafix-tests/output/src/main/scala-2.13/test/RemoveUnusedPatternVars.scala
This PR aims at fixing #1343 by using a more general regexp and adding several tests.
closes #1343
> Fix RemoveUnusedPatternVars

- scalafix-rules/src/main/scala/scala/meta/internal/proxy/GlobalProxy.scala
The bug doesn't seem to exist anymore.
This call was increasing the memory usage of ExpicitResultType
> Don't produce each time a RichCompilationUnit

- project/Dependencies.scala
Issue #1337 is caused by a regression introduced in scalameta/scalameta#2239, and got fixed by scalameta/scalameta#2260, which is included in Scalameta 4.4.11. This PR upgrades Scalameta to 4.4.12 to include the fix, so that issue #1337 can be resolved.
> Upgrade Scalameta to 4.4.12

- docs/users/installation.md
For snapshot releases, the `@NIGHTLY_VERSION@` string already contains the `-SNAPSHOT` suffix. The current version produces wrong outputs like the following:
```diff
// project/plugins.sbt
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.27")
+resolvers += Resolver.sonatypeRepo("snapshots")
+dependencyOverrides += "ch.epfl.scala" % "scalafix-interfaces" % "0.9.27+13-5a94c83f-SNAPSHOT-SNAPSHOT"
```
This PR removes the redundant `-SNAPSHOT` suffix.
> Fix snapshot version string in the Installation page

- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/ValidatedArgs.scala
- scalafix-core/src/main/scala/scalafix/v1/SemanticDocument.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/BaseSemanticSuite.scala
- instead we report an error of semanticdb files missing
> Don't generate semanticdb files if there are missing 

- project/Mima.scala
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
- scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixArguments.java
- scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/ArgsSuite.scala
it makes me release that sourceroot need also to be configured differently if the dialect Scala3.
There are two commits in this PR. The second is a proposition to make the targetroot configurable through the api
> Configure correctly semanticdb targetroot depending on the dialect

- docs/users/configuration.md
- docs/users/installation.md
ref: https://github.com/scalacenter/scalafix/pull/1217 https://github.com/scalacenter/sbt-scalafix/pull/169
This is a follow up PR to introduce `--triggered` args and `triggered` configuration prefix to run scalafix on compilation with different config.
> add triggered config description to docs

- build.sbt
- project/Mima.scala
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixArguments.java
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/AbstractSemanticRuleSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/BaseCliSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/BaseSemanticSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/PrettyTypeSuite.scala
Second take at https://github.com/scalacenter/scalafix/pull/1275 leveraging https://github.com/scalacenter/scalafix/pull/1389 (with the addition of the first preliminary commit, allowing the targetroot to be repeated in the CLI when dealing with a complex classpath)
Unlocks https://github.com/scalacenter/sbt-scalafix/pull/219
> testkit: extract targetroot from scalacOptions

- build.sbt
- project/Dependencies.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/DisableSyntaxConfigSuite.scala
Fix https://github.com/scalacenter/scalafix/issues/1414 before a release of metaconfig is cut with https://github.com/scalameta/metaconfig/pull/131
> Revert metaconfig 0.9.11 bump

- docs/users/installation.md
Blocked by https://github.com/scalacenter/sbt-scalafix-example/pull/4/commits/e5ea9a5b86401fe3e8c1176d7525a7859f9f1d0a
https://github.com/scalacenter/scalafix/blob/9af04d5d50983a079cffcc6631c2cf241be247af/scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala#L13-L17
> docs: stop using deprecated rule name

- docs/users/installation.md
https://github.com/scalacenter/sbt-scalafix/blob/c0b389fc409e1db6e55aac571a0b9aceca49c5fc/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L210
See also https://github.com/scalacenter/sbt-scalafix/pull/233
> doc: clarify where scalafixScalaBinaryVersion is looked up

- docs/rules/NoAutoTupling.md
- project/ScalafixBuild.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/NoAutoTupling.scala
- scalafix-tests/input/src/main/scala-2/test/noAutoTupling/NoAutoTupling.scala
- scalafix-tests/input/src/main/scala-2/test/noAutoTupling/NoUnitInsertion.scala
- scalafix-tests/output/src/main/scala-2.11/test/noAutoTupling/NoAutoTupling.scala
- scalafix-tests/output/src/main/scala-2.12/test/noAutoTupling/NoAutoTupling.scala
- scalafix-tests/output/src/main/scala-2.13/test/noAutoTupling/NoAutoTupling.scala
- scalafix-tests/output/src/main/scala-2/test/noAutoTupling/NoUnitInsertion.scala
- and refactoring tests
I don't know if want to insert `()` when we have this kind of warnings (that are only reported by `-deprecation`)
```
adaptation of an empty argument list by inserting () is deprecated: this is unlikely to be what you want
signature: Some.apply[A](value: A): Some[A]
given arguments: <none>
after adaptation: Some((): Unit)
```
The test was called NoUnitInsertion. Not clear for me if we want that or not. In the other hand, even if it's not a behavior we want, noAutoTupling insert (), if the user has added -deprecation in his options. It wasn't working for 2.13 since the warning message changed from `Adaptation ...` to `adaptation ...` for unit insertions.
- other point: For this rule, we don't have `withConfiguration`: should we do the same than in removeUnused ?
> Make NoAutoTupling fixes the insertion of unit

- docs/rules/RemoveUnused.md
- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnusedConfig.scala
- scalafix-tests/input/src/main/scala-2.12/test/removeUnused/RemoveUnusedImportsTrailingCommas.scala
- scalafix-tests/input/src/main/scala-2.12/test/removeUnused/RemoveUnusedParams.scala
- scalafix-tests/input/src/main/scala-2.12/test/removeUnused/RemoveUnusedPatternVars.scala
- scalafix-tests/input/src/main/scala-2.13/test/removeUnused/RemoveUnusedParams.scala
- scalafix-tests/output/src/main/scala-2.12/test/removeUnused/RemoveUnusedImportsTrailingCommas.scala
- scalafix-tests/output/src/main/scala-2.12/test/removeUnused/RemoveUnusedParams.scala
- scalafix-tests/output/src/main/scala-2.12/test/removeUnused/RemoveUnusedPatternVars.scala
- scalafix-tests/output/src/main/scala-2.13/test/removeUnused/RemoveUnusedParams.scala
Follows https://github.com/scalacenter/scalafix/pull/1444 (and https://github.com/scalacenter/scalafix/pull/1434 for the second commit)
Note that the current rule implementation does not generate invalid code, it just misses some rewrites.
> Unused function params follow-up

- docs/developers/symbol-information.md
- scalafix-core/src/main/scala/scalafix/v1/SymbolInformation.scala
`overriddenSymbols` field has been added to SymbolInformation recently, but there's no way to access the field from scalafix API at this moment. https://github.com/scalameta/scalameta/pull/2233
This PR adds an accessor to `overriddenSymbols` to `SymbolInformation`.
> Add accessor to `overriddenSymbols` to SymbolInformation

- .scala-steward.conf
closes https://github.com/scalacenter/scalafix/pull/1505
> don't bump JGit to keep Java 8 compatibility

- docs/rules/community-rules.md
Closes https://github.com/scalacenter/scalafix/pull/1539
Rationale: the list was getting longer and not fun to read so I decided to
- split it into 3 categories
- rephrase/simplify descriptions (removing mentions of "Scalafix" when redundant)
- use tables for more readability
- browse through scaladex to find a few new rules published and tested that I found worth sharing
> overhaul community rules page

- .github/workflows/deploy-website.yml
Since [versions](https://github.com/scalacenter/scalafix/blob/6c21e2662b0bec87e1495d14f20a775a10663ff9/project/ScalafixBuild.scala#L96-L98) used in docs (and in metadata available for clients) come from https://github.com/sbt/sbt-dynver, I don't understand how this ever worked with a shallow clone, so this might help with https://github.com/scalacenter/scalafix/issues/1538
> attempt at fixing versions in user-facing docs

- build.sbt
- scalafix-interfaces/src/main/java/scalafix/internal/interfaces/ScalafixCoursier.java
- scalafix-rules/src/main/scala-2.11/scalafix/internal/rule/TPrintImplicits.scala
- scalafix-rules/src/main/scala-2.12+/scalafix/internal/rule/TPrintImplicits.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntaxConfig.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitPath.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/TestkitProperties.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/core/PrettyTypeSuite.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/rule/MavenFuzzSuite.scala
Follows https://github.com/scalacenter/scalafix/pull/1530
Should unblock https://github.com/scalacenter/scalafix/pull/1531
Injecting instances of `pprint.TPrint` to customize the docs no longer has effect as of https://github.com/scalacenter/scalafix/pull/1530, which was a silent breaking change. This commit exposes the breaking change so that rules built against the latest scalafix-core either drop usage of `TPrint` or switch to the shaded version which is used internally by metaconfig.
> force usage of shaded TPrint

- scalafix-rules/src/main/scala-2.11/scalafix/internal/rule/TPrintImplicits.scala
- scalafix-rules/src/main/scala-2.12+/scalafix/internal/rule/TPrintImplicits.scala
Follows https://github.com/scalacenter/scalafix/pull/907
Discovered in https://github.com/scalacenter/scalafix/pull/1546#discussion_r805798333
https://scalacenter.github.io/scalafix/docs/rules/DisableSyntax.html
> `List[CustomMessage[Either[Regex, Pattern]]]`
>  fix docs: reflect new param signature after #907

- build.sbt
- project/plugins.sbt
Closes https://github.com/scalacenter/scalafix/pull/1548
Effectively reverts https://github.com/scalacenter/scalafix/commit/bdaadfde3314090d2759ff982f94649d317897fd since to my knowledge, it's not actively used (at least I don't)
> remove unused plugin

- project/Dependencies.scala
- scalafix-core/src/main/scala/scalafix/internal/util/DenotationOps.scala
In the Scala 2 community build, I noticed that 1) this upgrade hasn't happened here yet, and 2) it requires a small source change (because the deprecated `allowMethodTypes` was removed).
And then also I'm seeing failing tests downstream in simulacrum-scalafix, at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3535/artifact/logs/simulacrum-scalafix-build.log :
```
[simulacrum-scalafix] =======
[simulacrum-scalafix] => Diff
[simulacrum-scalafix] =======
[simulacrum-scalafix] --- obtained
[simulacrum-scalafix] +++ expected
[simulacrum-scalafix] @@ -24,9 +24,9 @@
[simulacrum-scalafix] âˆ™
[simulacrum-scalafix] -  val fk1 = Î»[FuncK[Option, List]](_.toList)
[simulacrum-scalafix] +  val fk1 = new FuncK[Option, List] { def apply[A$](a$: Option[A$]): List[A$] = …
```
> Scalameta 4.5.0 (was 4.4.35)

- scalafix-core/src/main/scala-2.12/scalafix/util/metaconfig/generic/package.scala
- scalafix-core/src/main/scala-2.13/metaconfig/generic/package.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ConfigRulePatches.scala
- scalafix-core/src/main/scala/scalafix/internal/config/DebugConfig.scala
- scalafix-core/src/main/scala/scalafix/internal/config/LintConfig.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-core/src/main/scala/scalafix/internal/util/MetaconfigCompatMacros.scala
Follows https://github.com/scalacenter/scalafix/pull/1530
`metaconfig-pprint` brought by `metaconfig-core` 0.10.0 will not be available to external rules when classloaded by an old `scalafix-cli` version as the runtime `scalafix-core` and its dependencies are driven by `scalafix-cli` dependencies, not the rule dependencies.
We obviously have no control over old `scalafix-cli` versions, but since the reference to the potentially-missing type is from a macro-generated block, this wraps it to provide a more actionable error message.
> better error for external rules ran with old scalafix-cli version

- .scala-steward.conf
Rationale: scalameta being at the heat of the Scalafix API, we should track the latest version
> never wait to bump scalameta

- .github/workflows/ci.yml
- .github/workflows/release.yml
- build.sbt
- docs/developers/api.md
- project/ScalafixBuild.scala
- project/plugins.sbt
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/util/Compatibility.scala
- scalafix-interfaces/src/main/java/scalafix/internal/interfaces/ScalafixCoursier.java
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CompatibilitySuite.scala
In the last few weeks, 2 dependency bumps broke backward compatibility of nightlies
- metaconfig 0.10.0, at the [source](https://github.com/scalacenter/scalafix/pull/1546) & [binary](https://github.com/scalacenter/scalafix/pull/1530#issuecomment-1061174301) level because of [breaking changes in pprint](https://github.com/com-lihaoyi/PPrint/pull/72), despite [attempts to mitigate the problem](https://github.com/scalameta/metaconfig/pull/154)
- scalameta 4.5.0, at the [functional](https://github.com/typelevel/simulacrum-scalafix/pull/194) level, by [introducing a new node in the AST](https://github.com/scalameta/scalameta/pull/2601) ([detected thanks to the Scala 2 community build](https://github.com/scalacenter/scalafix/pull/1556))
Since these changes haven't made it to a release yet, that …
> define & apply binary compatibility strategy

- docs/developers/local-rules.md
- docs/developers/tutorial.md
- docs/rules/community-rules.md
- docs/rules/external-rules.md
- docs/users/installation.md
Companion of
- https://github.com/scalacenter/sbt-scalafix/pull/281
- https://github.com/scalacenter/sbt-scalafix/pull/282
- https://github.com/scalacenter/sbt-scalafix/pull/291
> sbt-scalafix doc updates

- scalafix-rules/src/main/scala/scala/meta/internal/pc/Identifier.scala
- scalafix-rules/src/main/scala/scala/meta/internal/pc/ScalafixGlobal.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/CompilerTypePrinter.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesBackQuote.scala
- scalafix-tests/output/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesBackQuote.scala
This fixes #1219. I was struggled with a working fix for all type-symbols but didn't succeed. I'd be glad to get help in moving this onward.
> `ExplicitResultTypes`: backquote types when needed

- docs/developers/api.md
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/util/Compatibility.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CompatibilitySuite.scala
Follow-up of https://github.com/scalacenter/scalafix/pull/1565 (https://github.com/scalacenter/scalafix/commit/c4c1f1e686367f1bcf7d627526d93416fa8de07b#r69611050)
> only warn when loading rules built with newer core

- build.sbt
- scalafix-interfaces/src/main/java/scalafix/internal/interfaces/ScalafixCoursier.java
Follows https://github.com/scalacenter/scalafix/pull/1546
Tested against regressions via https://github.com/scalacenter/scalafix/blob/c5633c67a449b0ed8658c26910805f6893485007/scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala#L84-L95 (`com.nequissimus::sort-imports:0.5.2` is built against [0.9.x](https://github.com/NeQuissimus/sort-imports/blob/v0.5.2/project/plugins.sbt#L2))
> pprint is only required on -cli for 0.9.x compat

- docs/rules/community-rules.md
We are developing a generic rewriting rule for scalafix called [pixiv-scalafix-rule](https://github.com/pixiv/scalafix-pixiv-rule). This rule fixes redundant Scala code and anti-patterns.
We would like to add this rule to `community-rules.md` and introduce it in the official documentation because we want many people to use it.
> I want to add my rules to community-rules.md

- docs/rules/RedundantSyntax.md
- scalafix-rules/src/main/scala/scalafix/internal/rule/RedundantSyntax.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/RedundantSyntaxConfig.scala
- scalafix-tests/input/src/main/scala/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/output/src/main/scala/test/redundantSyntax/StringInterpolator.scala
Idea from [gitter](https://gitter.im/scalacenter/scalafix?at=625756193ae95a1ec1e78751):
```diff
- println(s"Hi!")
+ println("Hi!")
```
> RedundantSyntax removes unnecessary string interpolator

- scalafix-rules/src/main/scala/scala/meta/internal/pc/ScalafixGlobal.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesBackQuoteComplex.scala
- scalafix-tests/output/src/main/scala-2.11/test/explicitResultTypes/ExplicitResultTypesBackQuoteComplex.scala
- scalafix-tests/output/src/main/scala-2.12/test/explicitResultTypes/ExplicitResultTypesBackQuoteComplex.scala
- scalafix-tests/output/src/main/scala-2.13/test/explicitResultTypes/ExplicitResultTypesBackQuoteComplex.scala
I backported the changes to backquote types to Metals and found some issues. Some of that might not be needed for Scalafix, but it's better to be on the safe side.
Related https://github.com/scalameta/metals/pull/3829
> Fix issues with backquotes in several case as seen in Metals

- scalafix-rules/src/main/scala/scalafix/internal/rule/RedundantSyntax.scala
- scalafix-tests/input/src/main/scala/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/output/src/main/scala/test/redundantSyntax/StringInterpolator.scala
`RedundantSyntax` raised an exception for some characters
were escaped in a raw interpolator.
```
scalafix.internal.v1.FileException: unexpected error processing file /workspace/A.scala
Caused by: scala.StringContext$InvalidEscapeException: invalid escape '\+' not one of [\b, \t, \n, \f, \r, \\, \", \', \uxxxx] at index 4 in "(.*)\+.*@(.*)". Use \\ for literal \.
at scala.StringContext$.loop$2(StringContext.scala:417)
at scala.StringContext$.replace(StringContext.scala:429)
at scala.StringContext$.processEscapes(StringContext.scala:387)
at scalafix.internal.rule.RedundantSyntax$$anonfun$fix$1.applyOrElse(RedundantSyntax.scala:39)
```
> Fix RedundantSyntax raw interpolator handling

- scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypesConfig.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesOnlyImplicits.scala
- scalafix-tests/output/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesOnlyImplicits.scala
This is useful for scala3 migration since it requires explicit return types for implicits
> Add an option to only add explicit result types to implicit definitions

- scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala
Prevent potential regressions caused by https://github.com/scalacenter/scalafix/pull/1632#issuecomment-1185391771
Attempting to load a rule built with 0.10.0 on 0.10.x can help us identify classloading regressions that would violate https://scalacenter.github.io/scalafix/docs/developers/api.html#compatibility-considerations.
> test loading of external rule built with metaconfig hack

- CONTRIBUTING.md
- README.md
- scalafix-docs/src/main/scala/docs/Main.scala
- website/core/Footer.js
I recently learnt about the #scalafix channel on the Scalameta servers (advertized in https://www.scala-lang.org/blog/2021/12/21/discord.html#what-other-chat-servers-exist). I am not fully convinced Discord is the way to go (sharing the same opacity concerns as https://alexn.org/blog/2022/04/09/scala-gitter-discord-mistake/), but I think it's better to stay close to the Scalameta community. We should delete the gitter room once this is merged.
> Use scalameta's Discord rather than gitter for support

- docs/developers/tutorial.md
Fixed a couple of small discrepancies in the docs:
1 The diagnostic error states that this should be the error:
```
===========> Unreported <===========
test/NoLiteralArgumentsConfig.scala:16:20: error
complete("done") // assert: NoLiteralArguments
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
but given the  config and code provided:
```scala
/*
rule = NoLiteralArguments
NoLiteralArguments.disabledLiterals = [
Int
Boolean
]
*/
package test
class NoLiteralArgumentsConfig {
def complete(message: String): Unit = ()
def complete(count: Int): Unit = ()
def complete(isSuccess: Boolean): Unit = ()
complete("done") // ok, no error message
complete(42) // assert: NoLiteralArguments
complete(true) // assert: NoLiteralArguments
}
```
`complete("done")` should not report a lint error. (it also has the `// ok, no …
> Fix small issues with the tutorial docs

- docs/users/installation.md
This PR updates obsolete documentation: we don't need to wrap settings into `inConfig(config)` method because it's already done in `scalafixConfigSettings` [implementation](https://github.com/scalacenter/sbt-scalafix/blob/169fc60c58304df00835795f717b634329549312/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L82-L83):
```scala
def scalafixConfigSettings(config: Configuration): Seq[Def.Setting[_]] =
inConfig(config)(...)
```
> Update `Integration tests` documentation.

- build.sbt
- project/Dependencies.scala
- project/ScalafixBuild.scala
The scalatest version update, needed for the work done in https://github.com/scalacenter/scalafix/pull/1650 , specifically because the old scalatest version in not found anymore.
When updating the versions there's a lib version conflict on `scala-xml` which is resolved by ignoring with a `libraryDependencySchemes` as suggested in the conflict output below:
```
sbt:scalafix> unit2_12Target3/update
[error] stack trace is suppressed; run last unit2_12Target3 / update for the full output
[error] (unit2_12Target3 / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error]         * org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.0.6}
[error]             +- …
```
> Update unit module scalatest version to 3.2.13

- project/ScalafixBuild.scala
Follows https://github.com/scalacenter/scalafix/pull/1528/commits/e099cc451aa0e5252bc933a78dbc56a4cb571369#r846677704. This brings back time savings of ~1-2 minutes for `test` on cold invocations, but also on warm ones, as it seems that scaladoc is not incremental/cached.
This should also benefit https://github.com/scalacenter/scalafix/pull/1650, where [we observe exceptions generating docs with scala 3.2.0 on windows](https://github.com/scalacenter/scalafix/runs/8272351990):
```
[error] Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 30: scalafix/util/TreeExtractors$$:&&:$.html
[error] 	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[error] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[error] 	at …
```
> skip src and doc packaging when publishing locally

- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala
- fix https://github.com/scalacenter/scalafix/issues/1663
> support Scala 3 style wildcard import in RemoveUnused

- project/ScalafixBuild.scala
Blocks https://github.com/scalacenter/scalafix/issues/1668: snapshots are currently published, but we shouldn't be publishing stable releases just yet
```diff
sbt:scalafix> show publish / skip
...
[info] core3 / publish / skip
-[info] 	false
+[info] 	true
...
[info] rules3 / publish / skip
-[info] 	false
+[info] 	true
```
> don't publish scala 3 artifacts for now

- bin/test-release.sh
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-tests/unit/src/main/resources/expect/Pretty.expect
Fixes https://github.com/scalacenter/scalafix/issues/1673
Towards https://github.com/scalacenter/scalafix/issues/1675
> scala 2.13.9

- bin/test-release.sh
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-tests/unit/src/main/resources/expect/Pretty.expect
Towards https://github.com/scalacenter/scalafix/issues/1684
> scala 2.13.10

- scalafix-rules/src/main/scala-2/scalafix/internal/rule/ExplicitResultTypes.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesOnlyImplicits.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesSingleton.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ImplicitMembersWithSkipSimpleDefinition.scala
- scalafix-tests/output/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesBase.scala
- scalafix-tests/output/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesShort.scala
- scalafix-tests/output/src/main/scala-2/test/explicitResultTypes/ImplicitMembersWithSkipSimpleDefinition.scala
Fixes #1628 
The `skipSimpleDefinitions` configuration wasn't always applied correctly (specifically when members are implicit the configuration wasn't considered)
- A unit test for this specific case was added
- Old unit tests are fixed based on the default value of `skipSimpleDefinitions` or on the intent of the test
> ExplicitResultTypes: honor skipSimpleDefinitions on implicits

- scalafix-rules/src/main/scala/scalafix/internal/rule/RedundantSyntax.scala
- scalafix-tests/input/src/main/scala/test/redundantSyntax/FinalObject.scala
- scalafix-tests/input/src/main/scala/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/output/src/main/scala/test/redundantSyntax/FinalObject.scala
- scalafix-tests/output/src/main/scala/test/redundantSyntax/StringInterpolator.scala
As reported on [Discord](https://discord.com/channels/632642981228314653/632683673417678860/1044516936463155200) by @GoreNuru, `RedundantSyntax` couldn't be suppressed
> RedundantSyntax: honor suppression

- docs/developers/tutorial.md
https://github.com/scalacenter/scalafix-named-literal-arguments/pull/7, https://github.com/scalacenter/scalafix-named-literal-arguments/pull/8 & https://github.com/scalacenter/scalafix-named-literal-arguments/pull/9 (partially) have been squashed into the first commit.
> reflect history rewrite in git repo for tutorial

- build.sbt
- project/Dependencies.scala
Unlocked by https://github.com/scalacenter/scalafix/pull/1729
Note that this is only used for testing (coursier-interface is used otherwise).
> bump coursier

- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixImpl.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala
https://github.com/scalacenter/scalafix/pull/1729 dropped support for running Scalafix with Scala 2.11 but running against Scala 2.11 sources was still possible. However, since we no longer test scalafix-core and scalafix-rules against Scala 2.11 sources, it's safer to fail hard and ask the user to downgrade.
> fail hard when running against 2.11 sources

- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixFileEvaluationImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixPatchImpl.scala
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixTextEditImpl.scala
- scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixPatch.java
- scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixTextEdit.java
- scalafix-tests/unit/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala
Hi!  I'd like to be able to obtain (LSP style)  text edit like information (essentially representing a diff as a start position, end position, and insert text) from the scalafix api (specifically a given `ScalafixFileEvaluation`) - AFAICS something like this is currently not exposed (?).
I've created an implementation (the method is similar to `PatchInternals.tokenPatchApply`).  Though I've found some rules don't give the greatest results, for example patches from the `OptionWhenUnless` rule (from https://github.com/xuwei-k/scalafix-rules):
```
Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Concat(Remove(if∙[142..144)),Remove(∙∙[144..145))),Remove((∙[145..146))),Remove(4∙[146..147))),Remove(∙∙[147..148))),Remove(>∙[148 …
```
> Add textEdits method to ScalafixPatch

- .github/scripts/update.sc
- .github/workflows/sonatype-stats.yml
https://github.com/scalacenter/scalafix/actions/runs/4975179404/jobs/8902103997
```
Run .github/scripts/update.sc
.github/scripts/update.sc
shell: /usr/bin/bash -e {0}
env:
MSYS: winsymlinks:nativestrict
JAVA_HOME: /home/runner/.cache/coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz/jdk-17+35
COURSIER_BIN_DIR: /home/runner/cs/bin
SONATYPE_USERNAME: ***
SONATYPE_PASSWORD: ***
/usr/bin/env: ‘scala’: No such file or directory
Error: Process completed with exit code 127.
```
> Fix sonatype stats cron

- .github/workflows/release.yml
Fix regression introduced in https://github.com/scalacenter/scalafix/pull/1756/commits/34bf3d0910e021bd1a10fc77a3d762c9b4d2309c
https://github.com/scalacenter/sbt-scalafix/actions/runs/5152679793/jobs/9279036518?pr=346
> java.lang.UnsupportedClassVersionError: scalafix/interfaces/ScalafixMainCallback has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> build JARs against Java 8 for max compatibility

- .scala-steward.conf
- build.sbt
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/AbstractSemanticRuleSuite.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/AbstractSyntacticRuleSuite.scala
This is a source-breaking change for testkit users that were relying on the ScalaTest 3.0 package hierarchy, deprecated 3 years ago in 3.1 and removed in 3.2 (despite no major bump).
Scalafix rules were made available to ease that transition, see https://github.com/scalatest/autofix/tree/master.
Closes https://github.com/scalacenter/scalafix/issues/1662.
> testkit: build against ScalaTest 3.2

- project/ScalafixBuild.scala
By default, the behavior of `publishLocal` is following `publish / skip`.
(found out about this while browing 1.9.0 changelog, where `publishLocal / skip` is now honored but [defaults to `publish / skip`](https://github.com/sbt/sbt/blob/cab5c48e244543c92ae1e0a59d1a23778c626aed/main/src/main/scala/sbt/Defaults.scala#L2625))
> Remove redundant build setting

- .github/workflows/release.yml
> java target should only be driven scalacOptions

- .github/workflows/ci.yml
- CONTRIBUTING.md
- build.sbt
- project/ScalafixBuild.scala
This adds a command to replace the `scalafix-interfaces` brought in by `sbt-scalafix` with the local one. Rationale: observe impact of changes & detect regressions.
The implementation is not great as it's slow and mutates state, but I ran into dead-ends for the 2 alternatives I explored:
- injecting a custom `scalafix-interfaces.properties` to force the default scalafix-interfaces to load a custom scalafix-cli would require changes in the classloading logic to favor the custom property file over the one embedded in the JAR
- sbt-scalafix's `scalafixInterfacesProvider` could be rewired to `cli2_12/fullClasspath` with [some minor addition](https://github.com/scalacenter/sbt-scalafix/pull/351), but it would require turning `scalafixInterfacesProvider` into a task key, which is not possible …
> dogfooding: run scalafixAll with local scalafix-interfaces

- project/ScalafixBuild.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-rules/src/main/scala-2/scalafix/internal/pc/ScalafixGlobal.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/NoAutoTupling.scala
As OrganizeImports rewrite the entire block of imports, adhoc `// scalafix:ok` suppressions were effectively disabling it on the entire block.
> run OrganizeImports despite scala-collection-compat

- .github/workflows/ci.yml
[sbt's `session save`](https://github.com/scalacenter/scalafix/pull/1784/files#diff-cf70a614681abb9e33115a49e0b4a52865bdfcdb24c4c0df4af6546d92f88f5fR189) was seen updating `project/plugins.sbt` in a way that scalafmt does not like (missing trailing LF).
See https://github.com/scalacenter/scalafix/pull/1813#issuecomment-1626233607
> run command potentially changing build files last

- .scalafmt.conf
I think this is the cause of the error we're seeing in the [Scala
Steward](https://github.com/scalacenter/steward/actions/runs/5470172748/jobs/9959938109#step:5:870)
where the scala213 dialect has issues with the Scala 3 code. This small
changes just adds in some fileOverrides to make sure the scala-3 dirs
set the runner.dialect as scala3 instead of scala213.
> fix: ensure scala 3 dirs use scala3 dialect for scalafmt

- docs/developers/tutorial.md
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/GitHubUrlRule.scala
- scalafix-tests/integration/src/test/scala/scalafix/tests/config/GitHubUrlRuleSuite.scala
Referencing scalafix rules does not currently allow rules to be located in a package other than `fix`.
Eg. in [scio](https://github.com/spotify/scio/tree/main/scalafix/rules/src/main/scala/fix) we've grouped rules in packages corresponding to the breaking version.
This change allows to reference a rule based on its package name (stripping the required `fix` package prefix)
> Allow package when referencing rules in github

- NOTICE.md
Follows https://github.com/scalacenter/scalafix/pull/1480
cc @liancheng
> Original MIT license for OrganizeImports

- docs/developers/tutorial.md
Given the existing [tutorial](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#import-the-build) instructions when I run the `tests/test` command form inside the `scalafix-named-literal-arguments` directory I get the following sbt error
```
sbt:scalafix-named-literal-arguments> tests/test
[error] Expected ID character
[error] Not a valid command: tests (similar: tasks, set, last)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: tests (similar: test, testOnly, testOptions)
[error] tests/test
[error]
```
Updating the instructions to run the command from the `scalafix-named-literal-arguments/scalafix` directory fixes the issue.
```
~/sandbox/scalafix-named-literal-arguments-test/scalafix on main …
```
> update the directory to run the tests/test command from

- bin/test-release.sh
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-reflect/src/main/scala-2/scalafix/internal/reflect/RuleCompiler.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
Towards https://github.com/scalacenter/scalafix/issues/1860
> use & support scala 2.13.12

- .github/workflows/release.yml
Reverts scalacenter/scalafix#1781 as there is no way to force a class file version with scala 2.12 ([we can only use the `target` hint](https://github.com/scalacenter/scalafix/blob/3da6acdd9af4e77e40a6d9e9b88975de8b7e26a8/project/ScalafixBuild.scala#L62)). JDK11 being the default JVM of the coursier version brought by coursier/setup-action@v1, 2.12 artifacts are no longer compatible with JDK8 :8ball: 
Identified through sbt-scalafix JDK8 CI when bringing-in the latest scalafix-interfaces: https://github.com/scalacenter/sbt-scalafix/actions/runs/6114939069/job/16597532534?pr=368. It would obviously be better to have a check in the CI here, but I am not sure it's really worth it as we have that safety net anyway.
> Revert "java target should only be driven by scalacOptions"

- scalafix-testkit/src/main/scala/scalafix/testkit/RuleTest.scala
- scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala
- scalafix-tests/input/src/main/scala-2/test/Headers.scala
Resolves: https://github.com/scalacenter/scalafix/issues/1828
Pinging @bjaglin since you commented on the original issue. The only thing that is missing is a test, its my first time working on scalafix so not entirely sure where to put such a test and what type of test.
> Try to parse all valid Testkit HOCON comments

- project/Dependencies.scala
https://github.com/scala/community-build/issues/1673
> allow Scala nightlies via system properties

- scalafix-rules/src/main/scala/scalafix/internal/rule/RedundantSyntax.scala
- scalafix-tests/input/src/main/scala-2.12/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/input/src/main/scala-2.13/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/input/src/main/scala-3/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/output/src/main/scala-2.12/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/output/src/main/scala-2.13/test/redundantSyntax/StringInterpolator.scala
- scalafix-tests/output/src/main/scala-3/test/redundantSyntax/StringInterpolator.scala
:exploding_head: 
```scala
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 17.0.7).
Type in expressions for evaluation. Or try :help.
scala> s""" \n """ == """ \n """ 
val res0: Boolean = false
scala> s" \n " == " \n "
val res1: Boolean = true
scala> f""" \n """ == """ \n """
val res2: Boolean = false
scala> f" \n " == " \n "
val res3: Boolean = true
scala> raw""" \n """ == """ \n """
val res4: Boolean = true
scala> raw" \n " == " \n "
val res5: Boolean = false
```
Test input/output had to be duplicated because 2.12 does not support `s"my \"quoted\" string"`
> RedundantSyntax: distinguish single and triple quotes

- scalafix-core/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-tests/input/src/main/scala/test/disableSyntax/DisableSyntaxBase.scala
Fix https://github.com/scalacenter/scalafix/issues/1889
> rules capturing leading tokens can be suppressed with scalafix:ok

- .gitignore
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixPatchImpl.scala
- scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixPatch.java
- scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala
Hi, I thought it might be helpful to surface whether or not a patch is atomic in the `ScalafixPatch` API.  The idea is this indicates whether or not this patch makes sense to apply in isolation (e.g. through the `textEdits` method).
Thanks!
> Add isAtomic to ScalafixPatch interface

- CONTRIBUTING.md
- scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala
The [Built-in Rules](https://scalacenter.github.io/scalafix/docs/rules/overview.html) section of the docs shows an empty description for the `OrganizeImports` rule.
> Add description to the OrganizeImports rule

- scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-tests/integration/src/test/scala-2/scalafix/tests/cli/CliSyntacticSuite.scala
Previously, scripts would not be supported. Now, they should be correctly picked up by Scalafix.
I also tested it in Metals with the organize imports rule.
Fixes https://github.com/scalacenter/scalafix/issues/1534
> improvement: Support script files

- .scalafix-scala2.conf
- .scalafix-scala3.conf
- project/ScalafixBuild.scala
- scalafix-core/src/main/scala-3/scalafix/util/CompatSemanticdbType.scala
- scalafix-reflect/src/main/scala-3/scalafix/internal/reflect/RuleCompiler.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala
- scalafix-tests/integration/src/test/scala-3/scalafix/tests/util/compat/CompatSemanticdb.scala
Goal: get (a little) more coverage for free
Follows https://github.com/scalacenter/scalafix/pull/1784 & https://github.com/scalacenter/scalafix/pull/1896
> run scalafix on Scala 3 sources

- .github/workflows/ci.yml
There is no reason to stick to JDK17 - if we pick one we'd better pick the latest. Also, it might speed up slightly the build...
Follows https://github.com/scalacenter/scalafix/pull/1810
> run windows CI with latest LTS JDK21

- build.sbt
Follows https://github.com/scalacenter/scalafix/pull/1728
> avoid flood of unused compiler warnings

- scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala
At best, this was causing memory leaks during an invocation. At worst, it was generating false negatives for unused import removals.
Exposed by https://github.com/scalacenter/scalafix/pull/1800/files#r1477081552
> OrganizeImports: don't leak state from one fix execution to another

- .scalafix-scala2.conf
- .scalafix-scala3.conf
- scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitDiff.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/EscapeHatch.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/PatchInternals.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/ReplaceSymbolOps.scala
- scalafix-core/src/main/scala/scalafix/internal/util/Pretty.scala
- scalafix-core/src/main/scala/scalafix/internal/util/PrettyType.scala
- scalafix-core/src/main/scala/scalafix/internal/util/SymbolOps.scala
- scalafix-core/src/main/scala/scalafix/internal/v0/LegacyCodePrinter.scala
- scalafix-core/src/main/scala/scalafix/util/TreeOps.scala
- scalafix-reflect/src/main/scala-3/scalafix/internal/reflect/RuleCompiler.scala
- scalafix-reflect/src/main/scala/scalafix/internal/reflect/RuleInstrumentation.scala
- scalafix-rules/src/main/scala-2/scalafix/internal/rule/CompilerTypePrinter.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/DisableSyntax.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/NoAutoTupling.scala
- scalafix-tests/expect/src/test/scala/scalafix/tests/rule/RuleSuite.scala
- scalafix-tests/integration/src/main/scala/scalafix/test/ExplicitSynthetic.scala
- scalafix-tests/integration/src/main/scala/test/TypeToTreeInput.scala
- scalafix-tests/integration/src/test/scala-2/scalafix/tests/cli/BaseCliSuite.scala
- scalafix-tests/integration/src/test/scala-2/scalafix/tests/core/PrettyTypeSuite.scala
- scalafix-tests/integration/src/test/scala/scalafix/tests/cli/ScalafixImplSuite.scala
- scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixArgumentsSuite.scala
Follows https://github.com/scalacenter/scalafix/pull/1918, https://github.com/scalacenter/scalafix/pull/1728 & https://github.com/scalacenter/scalafix/pull/1800
> run RemoveUnused

- build.sbt
- project/Dependencies.scala
- scalafix-core/src/main/scala/org/langmeta/internal/ScalametaInternals.scala
- scalafix-core/src/main/scala/scala/meta/internal/scalafix/ScalafixScalametaHacks.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala
- scalafix-docs/src/main/scala/scala/meta/internal/prettyprinters/Enquote.scala
https://github.com/scalameta/scalameta/releases/tag/v4.9.0
https://github.com/scalameta/scalameta/issues/3425 is a non-backward compatible feature, as quasiquotes expand to code referencing `scala.meta.trees.Origin` [which does not exist in 4.8.x](https://github.com/scalameta/scalameta/pull/3454).
This means that Scalafix rules containing quasiquotes compiled against scalameta 4.9.x will cause link errors if ran on older Scalafix versions. As a result, we need a minor Scalafix bump when taking that in, despite the fact [that it's "just" a minor bump in a SemVer lib](https://github.com/scalameta/scalameta/blob/6699cdedf3dd855e52254a2ed059c34554d09bb0/build.sbt#L667) (we could argue that a major bump of scalameta was needed, but backward compatibility guarantees with macros is not very well …
> scalameta 4.9.x

- docs/users/installation.md
Companion for https://github.com/scalacenter/sbt-scalafix/pull/380.
As usual with docs, let's hold the merge until the next release.
> document new ability to customize ScalafixInterface at project-level

- project/Dependencies.scala
https://github.com/scalameta/scalameta/releases/tag/v4.9.1-RC1
Brings-in https://github.com/scalameta/scalameta/pull/3581
> Scalameta 4.9.1-RC1

- docs/rules/OrganizeImports.md
https://contributors.scala-lang.org/t/transfer-of-lampepfl-dotty-to-scala-scala3-in-progress
> docs: remove references to dotty

- scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala
When specifying '-Wunused:import' with Scala 3.4.0, the following error occurs, so I think '-Wunused:imports' is the correct option.
```
invalid choice(s) for -Wunused: import
scalac -help  gives more information
```
> OrganizeImports: fix invalid recommended scalac option

- docs/users/installation.md
https://github.com/scalacenter/sbt-scalafix/pull/404 effectively [removes the ability to define project-level `scalafixResolvers`](https://github.com/scalacenter/sbt-scalafix/pull/404/files#diff-06169c9b17ca1913e8659adfb6e67d1360dcfadd638128457e2d74a9e4dcc72aR440), but it was not working for some cases (with local rules), and I think it's really not needed anyway.
> update docs to document that sbt resolvers are now handled

- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
- scalafix-tests/input/src/main/scala-3/test/removeUnused/RemoveUnusedSignificantIndentation.scala
- scalafix-tests/input/src/main/scala/test/removeUnused/RemoveUnusedTerms.scala
- scalafix-tests/output/src/main/scala-3/test/removeUnused/RemoveUnusedSignificantIndentation.scala
- scalafix-tests/output/src/main/scala/test/removeUnused/RemoveUnusedTerms.scala
Closes https://github.com/scalacenter/scalafix/issues/914
Adds `locally` to Term.Block RHS to avoid affecting lines above, precisely as described in the [scaladoc example](https://github.com/scala/scala/blob/a5270194b6eec9678a79e2f88a83d83aa6b92de1/src/library/scala/Predef.scala#L223-L246).
> RemoveUnused: guard Term.Block RHS in unused Defn

- docs/developers/local-rules.md
- docs/developers/setup.md
- docs/users/installation.md
- project/ScalafixBuild.scala
Companion for https://github.com/scalacenter/sbt-scalafix/pull/419
> sbt-scalafix scalafixScalaBinaryVersion is now deprecated

- scalafix-reflect/src/main/scala-3/scalafix/internal/reflect/RuleCompiler.scala
- scalafix-rules/src/main/scala-2/scalafix/internal/rule/ExplicitResultTypes.scala
Missed in https://github.com/scalacenter/scalafix/pull/1990
> remove references to sbt-only, deprecated key

- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixConfig.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/ScalafixConfigSuite.scala
https://github.com/scalacenter/scalafix/issues/2000#issuecomment-2191815501
> remove unused attributes

- docs/rules/OrganizeImports.md
- docs/rules/RemoveUnused.md
- scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala
- scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala
> handle unused warnings for sources compiled with upcoming LTS 3.3.4

- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-core/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala
- scalafix-core/src/main/scala/scalafix/internal/patch/LegacyPatchOps.scala
- scalafix-core/src/main/scala/scalafix/internal/util/DenotationOps.scala
- scalafix-core/src/main/scala/scalafix/internal/util/ProductStructure.scala
- scalafix-core/src/main/scala/scalafix/patch/Patch.scala
- scalafix-reflect/src/main/scala/scalafix/internal/v0/LegacyInMemorySemanticdbIndex.scala
- scalafix-tests/integration/src/main/scala/scalafix/test/ScalatestAutofixRule.scala
Rationale
- test against LTS & Next -> test the 2 Scala3 versions we can expect in the wild
- build with LTS -> prepare for https://github.com/scalacenter/scalafix/issues/1680
TODO
```diff
sbt:scalafix> projects
[info] In file:/home/brice/git/scala/scalafix/
[info] 	   cli2_12
[info] 	   cli2_13
[info] 	   cli3
[info] 	   core2_12
[info] 	   core2_13
[info] 	   core3
[info] 	   docs2_13
[info] 	   expect2_12Target2_12_18
[info] 	   expect2_12Target2_12_19
[info] 	   expect2_12Target2_12_19xsource3
[info] 	   expect2_13Target2_13_12
[info] 	   expect2_13Target2_13_13
[info] 	   expect2_13Target2_13_14
[info] 	   expect2_13Target2_13_14xsource3
+[info] 	   expect2_13Target3_3_4-RC1
[info] 	   expect2_13Target3_4_2
-[info] 	   expect3Target3_4_2
+[info] 	   expect3Target3_3_4-RC1
[info] …
```
> Scala3: test against both LTS & Next, build with LTS

- .github/workflows/deploy-website.yml
Follows https://github.com/scalacenter/scalafix/pull/1827, which was not working as any push on master would wipe stats out.
> preserve sonatype-stats dir when publishing docs

- project/plugins.sbt
Follows https://github.com/scalacenter/scalafix/pull/2036
See https://github.com/xerial/sbt-sonatype/issues/507
The regression is not visible on master  as the new client is apparently not used for OSS snapshots.
> bump sbt-ci-release to fix JDK8 support

- build.sbt
- project/Dependencies.scala
Introduced in https://github.com/scalacenter/scalafix/commit/162db399bbf5584632e617bf7c3135a600dc06c8, but not actively used. Removal missed in https://github.com/scalacenter/scalafix/commit/e6bd39bcd70a31069b4dd8269b53a99627b8a5c6.
> remove unused scala-java8-compat

- build.sbt
- project/Dependencies.scala
- scalafix-core/src/main/scala/scala/meta/internal/symtab/SymbolTable.scala
Follows https://github.com/scalacenter/scalafix/pull/2047 / https://github.com/scalameta/scalameta/pull/3747
See initial discussion in https://github.com/scalacenter/scalafix/pull/2024#discussion_r1703407620
> core: reduce amount of scalac dependencies

- docs/users/installation.md
- the output is specific to Scala 2
- sbt's SemanticdbPlugin is now the only documented setup and is trivial
> docs: remove stale instructions to verify setup

- docs/users/configuration.md
- docs/users/suppression.md
Closes https://github.com/scalacenter/scalafix/issues/2000
> docs: explain how users can customize linting behavior of rules

- project/Dependencies.scala
- scalafix-rules/src/main/scala-2/scalafix/internal/rule/ExplicitResultTypes.scala
https://github.com/scalameta/scalameta/issues/3913 adds new elements in the tree hierarchy, effectively chaning the parents of
- https://github.com/scalameta/scalameta/pull/3928 (changes needed in this PR)
- `Template.stats` 
- https://github.com/scalameta/scalameta/pull/3916
- `Ctor.Secondary.stats` 
- https://github.com/scalameta/scalameta/pull/3927
- `Type.Match.cases` 
- https://github.com/scalameta/scalameta/pull/3929
- `Type.Refine.stats` 
- `Type.Existential.stats` 
- `Pkg.stats` 
- `Template.early`
- https://github.com/scalameta/scalameta/pull/3917
- `Term.Match.cases`
- `Term.Try.catchp`
- ~`Term.PartialFunction.cases`~ (reverted in https://github.com/scalameta/scalameta/pull/3937)
- https://github.com/scalameta/scalameta/pull/3925
- `Term.For.enums`
- `Term.ForYield.enums`
> latest scalameta introduces new items in tree hierarchy

- .github/scripts/update.sc
- bin/test-release.sh
- project/Dependencies.scala
- project/ScalafixBuild.scala
- scalafix-tests/input/src/main/scala/test/removeUnused/RemoveUnusedPatternVars.scala
- scalafix-tests/integration/src/main/resources-2/expect/Pretty.expect
- scalafix-tests/output/src/main/scala-2/test/removeUnused/RemoveUnusedPatternVars.scala
- scalafix-tests/output/src/main/scala-3/test/removeUnused/RemoveUnusedPatternVars.scala
> build with and test against Scala 2.12.20 & 2.13.15

- project/Dependencies.scala
https://github.com/scalameta/scalameta/releases/tag/v4.10.0
Follows https://github.com/scalacenter/scalafix/pull/2047
Breaking changes already handled in https://github.com/scalacenter/scalafix/pull/2079
> scalameta 4.10.0

- scalafix-core/src/main/scala/scalafix/internal/config/ScalaVersion.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/ScalaVersionSuite.scala
Spin off from https://github.com/scalacenter/scalafix/pull/2023 since it's no longer needed there following rebases bringing final releases, but it can be useful in the future
> allow to use RC versions in arguments

- .jvmopts
Lately, we have seen many warnings like this on JDK8.
```
[warn] In the last 10 seconds, 8.954 (97.6%) were spent in GC. [Heap: 0.20GB free of 1.76GB, max 1.78GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
```
The cardinality/complexity of the build has greatly increased with https://github.com/scalacenter/scalafix/pull/2034 and https://github.com/scalacenter/scalafix/pull/2023, so it's probably time for a little refresh of the JVM options.
> tweak JVM options to better handle project cardinality

- docs/users/installation.md
Since https://github.com/scalacenter/scalafix/pull/2034, `cs install` brings a Scala 3 Scalafix by default, as coursier uses the latest Scala version available. Since many users are still on 2.13, this clarify when and how the corresponding Scala 2.13 artifact can be installed.
> explain when and how to run CLI with a given Scala version

- build.sbt
- project/Dependencies.scala
- project/Mima.scala
- project/ScalafixBuild.scala
- scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixImpl.scala
- scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java
- scalafix-tests/input/src/main/scala-3next/test/explicitResultTypes/Scala3_6OrGreater.scala
- scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala
- scalafix-tests/output/src/main/scala-3next/test/explicitResultTypes/Scala3_6OrGreater.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/cli/InterfacesPropertiesSuite.scala
Keep building for Scala 3.5 until the next minor version for backward compatibility.
⚠️ at least https://github.com/scalacenter/scalafix/issues/2138 remains a problem
> build with and test against Scala 3.6.2

- project/Dependencies.scala
- scalafix-tests/input/src/main/scala-3next/test/explicitResultTypes/Scala3_6OrGreater.scala
- scalafix-tests/output/src/main/scala-3next/test/explicitResultTypes/Scala3_6OrGreater.scala
Brings in https://github.com/scalameta/scalameta/pull/4092
Fixes https://github.com/scalacenter/scalafix/issues/2138
> use latest scalameta for better SIP-64 support

- scalafix-core/src/main/scala/scalafix/internal/config/ScalaVersion.scala
- scalafix-tests/unit/src/test/scala/scalafix/tests/config/ScalaVersionSuite.scala
Fixes #2112
Successfully tested locally with
```
$ sbt -Dscala3.nightly=3.6.4-RC1-bin-20241223-4d3f757-NIGHTLY expect3_6_4_RC1_bin_20241223_4d3f757_NIGHTLYTarget3_6_4-RC1-bin-20241223-4d3f757-NIGHTLY/test
...
[info] Run completed in 8 seconds, 698 milliseconds.
[info] Total number of tests run: 135
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 135, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 46 s, completed Dec 29, 2024, 9:53:37 PM
```
> support target files built with nightly Scala 3 compiler version

- project/Dependencies.scala
Many bugfixes, but highlight for Scala 3.6.2 is
- https://github.com/scalameta/scalameta/pull/4105
- https://github.com/scalameta/scalameta/issues/4093
> bump scalameta for SIP-58 & better SIP-64 syntax

- project/ScalafixBuild.scala
Since 3f644e7, save-expect would only run for Scala 2 despite saying it was running only for Scala 3. Better stay away from using "all" with input tasks.
> fix save-expect again

- .github/workflows/ci.yml
- project/ScalafixBuild.scala
- scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala
> test JDK23

- docs/users/installation.md
https://github.com/VirtusLab/scala-cli/issues/647 is out since scala-cli 1.6.1
> docs: advertize scala-cli integration

- scalafix-rules/src/main/scala-2/scalafix/internal/pc/ScalafixGlobal.scala
- scalafix-tests/input/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesBase.scala
- scalafix-tests/output/src/main/scala-2/test/explicitResultTypes/ExplicitResultTypesBase.scala
TypeName / TermName constructor does not run NameTransformer. The issue was that the type had encoded names while we used plain: Ours `TermName(-)` vs `TermName($minus)`
> ExplicitResultTypes: annotate members with symbolic names on Scala 2

- scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java
Fix drift introduced in https://github.com/scalacenter/scalafix/pull/2034
> align param name with javadoc

- project/ScalafixBuild.scala
JDK22 is [no longer built](https://github.com/scalacenter/scalafix/pull/2075), and it seems that we can compile 2.12.18 on JDK23
> remove obsolete filter

- build.sbt
sbt-scalafix will exclude that new artifact by blocking transitive dependency of interfaces, forcing users to explicitly pick a version for runtime.
Helps for https://github.com/scalacenter/sbt-scalafix/pull/482
Towards https://github.com/scalacenter/scalafix/issues/1146
> spin off properties to a separate artifact

- build.sbt
- scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java
- scalafix-interfaces/src/main/java/scalafix/internal/interfaces/ScalafixCoursier.java
Helps for https://github.com/scalacenter/sbt-scalafix/pull/482
Towards https://github.com/scalacenter/scalafix/issues/1146
Follows https://github.com/scalacenter/scalafix/pull/2226
This non-deterministic fallback will allow scalafixEnable to work in sbt-scalafix even though no scalafix-interfaces was explicitly provided.
> allow usage of scalafix-interfaces without scalafix-properties

- build.sbt
- scalafix-interfaces/src/main/java/scalafix/internal/interfaces/ScalafixCoursier.java
Follows https://github.com/scalacenter/scalafix/pull/2231
Helps for https://github.com/scalacenter/scalafix/pull/2223 & https://github.com/scalacenter/scalafix/pull/2211
> make test resilient to scala upgrades beyond 0.14.3

- build.sbt
- scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java
- scalafix-interfaces/src/main/java/scalafix/internal/interfaces/ScalafixCoursier.java
The initial approach for https://github.com/scalacenter/scalafix/issues/1146 started in https://github.com/scalacenter/scalafix/pull/2226, https://github.com/scalacenter/scalafix/pull/2231 & https://github.com/scalacenter/scalafix/pull/2233 [is being revised](https://github.com/scalacenter/sbt-scalafix/pull/482#issuecomment-2817172495) in https://github.com/scalacenter/scalafix/pull/2236.
However, that PR is not ready and we want to cut a release [for 3.7.0](https://github.com/scalacenter/scalafix/pull/2211) ASAP, so this reverts the corresponding PRs since they introduced the artifact scalafix-properties that is likely to be removed and superseeded by scalafix-versions (and is not used as it was never published as a stable release).
> Revert scalafix-properties PRs

- CONTRIBUTING.md
Tests such as
```bash
> unit3_3_4 / test
```
as mentioned in `CONTRIBUTING.md` don't readily run.
```bash
sbt:scalafix> unit3_3_4 / test
[error] Expected ID character
[error] Not a valid command: unit3_3_4
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: unit3_3_4
[error] unit3_3_4 / test
[error]     
```
Version `3.3.4` is no longer available in the jvm versions.
> Update JVM versions in contributing docs
